import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { useAuth } from './AuthContext';

export type Locale = 'en' | 'fr' | 'pt' | 'ar' | 'es' | 'zh' | 'hi' | 'rw' | 'sw' | 'am' | 'ha' | 'yo' | 'zu' | 'ig';

interface LanguageContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Locale, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    crop_doctor: "Crop Doctor",
    recovery_tracker: "Recovery Tracker",
    daily_tasks: "Daily Tasks",
    weather: "Weather",
    guidance: "Guidance",
    ai_coach: "AI Coach",
    account: "Account",
    logout: "Logout",
    field_overview: "Field Overview",
    good_morning: "Good morning, Farmer.",
    promising_growth: "Your fields are showing promising growth today.",
    diagnostic_activity: "Your Diagnostic Activity",
    live_conditions: "Live Conditions",
    weather_outlook: "Weather Outlook",
    partly_cloudy: "Partly Cloudy",
    current_monitoring: "Current Monitoring",
    view_all_observations: "View All Observations",
    total_diagnoses: "Total Diagnoses",
    active_recovery: "Active Recovery",
    health_score: "Field Health Score",
    efficiency_bonus: "Efficiency",
    ask_anything: "Ask anything...",
    send: "Send",
    scanning: "Analyzing your crop...",
    diagnosis_found: "AI DIAGNOSIS FOUND",
    confidence: "Confidence",
    recovery_journal: "Would you like to start a recovery journal for this crop?",
    start_monitoring: "Start Monitoring",
    another_specimen: "Analyze Another Specimen",
    language: "Language",
    theme: "Theme",
    dark_mode: "Dark Mode",
    light_mode: "Light Mode",
    navigation: "Navigation",
    mon: "Mon",
    tue: "Tue",
    wed: "Wed",
    thu: "Thu",
    fri: "Fri",
    sat: "Sat",
    sun: "Sun",
    crop_care: "Crops under your care",
    recovering_robust: "Recovering & Robust",
    dashboard_short: "Feed",
    scan_short: "Scan",
    crops_short: "Crops",
    plan_short: "Plan",
    you_short: "You",
    coach_greeting: "Good morning. I'm your digital agricultural coach. Whether it's a suspicious leaf pattern or climate concerns, I'm here to think through it with you. How is your field today?",
    coach_error: "I encountered a minor connection issue. Shall we try that thought again?",
    great_shot: "Great shot.",
    check_crops_title: "Let's check your crops.",
    ready_opinion: "Ready for an expert opinion? Our AI is standing by.",
    capture_photo_tip: "Capture a clear photo of the leaves or stem. We'll identify any issues in seconds.",
    confirm_analyze: "Confirm & Analyze",
    identifying_patterns: "\"Identifying patterns invisible to the human eye. Almost there.\"",
    save_diagnosis: "Save Diagnosis to History",
    diagnosis_saved: "Diagnosis saved to history."
  },
  fr: {
    dashboard: "Tableau de Bord",
    crop_doctor: "Docteur de Culture",
    recovery_tracker: "Suivi de Récupération",
    daily_tasks: "Tâches Quotidiennes",
    weather: "Météo",
    guidance: "Conseils",
    ai_coach: "Coach IA",
    account: "Compte",
    logout: "Déconnexion",
    field_overview: "Aperçu du Champ",
    good_morning: "Bonjour, Fermier.",
    promising_growth: "Vos champs montrent une croissance prometteuse aujourd'hui.",
    diagnostic_activity: "Votre Activité Diagnostique",
    live_conditions: "Conditions en Direct",
    weather_outlook: "Perspectives Météo",
    partly_cloudy: "Partiellement Nuageux",
    current_monitoring: "Surveillance Actuelle",
    view_all_observations: "Voir Toutes les Observations",
    total_diagnoses: "Diagnostics Totaux",
    active_recovery: "Récupération Active",
    health_score: "Score de Santé du Champ",
    efficiency_bonus: "Efficacité",
    ask_anything: "Demandez n'importe quoi...",
    send: "Envoyer",
    scanning: "Analyse de votre récolte...",
    diagnosis_found: "DIAGNOSTIC IA TROUVÉ",
    confidence: "Confiance",
    recovery_journal: "Souhaitez-vous commencer un journal de récupération pour cette culture ?",
    start_monitoring: "Commencer la Surveillance",
    another_specimen: "Analyser un Autre Spécimen",
    language: "Langue",
    theme: "Thème",
    dark_mode: "Mode Sombre",
    light_mode: "Mode Clair",
    navigation: "Navigation",
    mon: "Lun",
    tue: "Mar",
    wed: "Mer",
    thu: "Jeu",
    fri: "Ven",
    sat: "Sam",
    sun: "Dim",
    crop_care: "Cultures sous votre garde",
    recovering_robust: "En récupération & Robustes",
    dashboard_short: "Flux",
    scan_short: "Scanner",
    crops_short: "Cultures",
    plan_short: "Plan",
    you_short: "Vous"
  },
  ar: {
    dashboard: "لوحة القيادة",
    crop_doctor: "طبيب المحاصيل",
    recovery_tracker: "متتبع التعافي",
    daily_tasks: "المهام اليومية",
    weather: "الطقس",
    guidance: "التوجيه",
    ai_coach: "مدرب الذكاء الاصطناعي",
    account: "الحساب",
    logout: "تسجيل الخروج",
    field_overview: "نظرة عامة على الحقل",
    good_morning: "صباح الخير أيها المزارع.",
    promising_growth: "تظهر حقولك نموًا واعدًا اليوم.",
    diagnostic_activity: "نشاطك التشخيصي",
    live_conditions: "الظروف المباشرة",
    weather_outlook: "توقعات الطقس",
    partly_cloudy: "غائم جزئيًا",
    current_monitoring: "المراقبة الحالية",
    view_all_observations: "عرض جميع الملاحظات",
    total_diagnoses: "إجمالي التشخيصات",
    active_recovery: "التعافي النشط",
    health_score: "درجة صحة الحقل",
    efficiency_bonus: "الكفاءة",
    ask_anything: "اسأل أي شيء...",
    send: "إرسال",
    scanning: "تحليل محصولك...",
    diagnosis_found: "تم العثور على تشخيص الذكاء الاصطناعي",
    confidence: "الثقة",
    recovery_journal: "هل ترغب في بدء سجل تعافي لهذا المحصول؟",
    start_monitoring: "بدء المراقبة",
    another_specimen: "تحليل عينة أخرى",
    language: "اللغة",
    theme: "المظهر",
    dark_mode: "الوضع الداكن",
    light_mode: "الوضع الفاتح",
    navigation: "التنقل",
    mon: "الإثنين",
    tue: "الثلاثاء",
    wed: "الأربعاء",
    thu: "الخميس",
    fri: "الجمعة",
    sat: "السبت",
    sun: "الأحد",
    crop_care: "المحاصيل تحت رعايتك",
    recovering_robust: "تتعافى وقوية",
    dashboard_short: "الخلاصة",
    scan_short: "مسح",
    crops_short: "المحاصيل",
    plan_short: "خطة",
    you_short: "أنت"
  },
  rw: {
    dashboard: "Inshamake",
    crop_doctor: "Muganga w'imyaka",
    recovery_tracker: "Gukurikirana imyaka",
    daily_tasks: "Imirimo y'uyu munsi",
    weather: "Iteganyagihe",
    guidance: "Inama",
    ai_coach: "Agasobanuye",
    account: "Konti",
    logout: "Sohoka",
    field_overview: "Ibyerekeye umurima",
    good_morning: "Mwaramutse, Muhinzi.",
    promising_growth: "Imyaka yawe iragaragaza gukura neza uyu munsi.",
    diagnostic_activity: "Ibihe by'isuzuma ryawe",
    live_conditions: "Ibihe by'ubu",
    weather_outlook: "Iteganyagihe",
    partly_cloudy: "Hari ibicu",
    current_monitoring: "Ibirimo gukurikiranwa",
    view_all_observations: "Reba byose",
    total_diagnoses: "Isuzumwa ryose",
    active_recovery: "Irimo gukira",
    health_score: "Amanota y'ubuzima bw'umurima",
    efficiency_bonus: "Umusaruro",
    ask_anything: "Baza ikibazo cyose...",
    send: "Ohereza",
    scanning: "Irimo gusuzuma ibihingwa byanyu...",
    diagnosis_found: "ISUZUMWA RYA AI RYABONETSE",
    confidence: "Icyizere",
    recovery_journal: "Wifuza gutangira inyandiko yo gukurikirana iki gihingwa?",
    start_monitoring: "Tangira gukurikirana",
    another_specimen: "Susa ikindi gihingwa",
    language: "Ururimi",
    theme: "Igaragara",
    dark_mode: "Umwijima",
    light_mode: "Urumuri"
  },
  sw: {
    dashboard: "Dashibodi",
    crop_doctor: "Daktari wa Mazao",
    recovery_tracker: "Ufuatiliaji wa Uponyaji",
    daily_tasks: "Kazi za Kila Siku",
    weather: "Hali ya Hewa",
    guidance: "Mwongozo",
    ai_coach: "Kocha wa AI",
    account: "Akaunti",
    logout: "Ondoka",
    field_overview: "Maelezo ya Shamba",
    good_morning: "Habari za asubuhi, Mkulima.",
    promising_growth: "Mashamba yako yanaonyesha ukuaji wa kuridhisha leo.",
    diagnostic_activity: "Shughuli zako za Utambuzi",
    live_conditions: "Hali ya Sasa",
    weather_outlook: "Mtazamo wa Hali ya Hewa",
    partly_cloudy: "Mawingu kiasi",
    current_monitoring: "Ufuatiliaji wa Sasa",
    view_all_observations: "Tazama Maoni Yote",
    total_diagnoses: "Jumla ya Utambuzi",
    active_recovery: "Uponyaji Amilifu",
    health_score: "Alama ya Afya ya Shamba",
    efficiency_bonus: "Ufanisi",
    ask_anything: "Uliza chochote...",
    send: "Tuma",
    scanning: "Kuchunguza zao lako...",
    diagnosis_found: "UTAMBUZI WA AI UMEREPATIKANA",
    confidence: "Uhakika",
    recovery_journal: "Je, ungependa kuanza rekodi ya uponyaji kwa zao hili?",
    start_monitoring: "Anza Kufuatilia",
    another_specimen: "Chunguza Sampuli Nyingine",
    language: "Lugha",
    theme: "Mandhari",
    dark_mode: "Hali ya Giza",
    light_mode: "Hali ya Mwanga"
  },
  pt: {
    dashboard: "Painel",
    crop_doctor: "Doutor de Culturas",
    recovery_tracker: "Rastreador de Recuperação",
    daily_tasks: "Tarefas Diárias",
    weather: "Clima",
    guidance: "Orientação",
    ai_coach: "Coach de IA",
    account: "Conta",
    logout: "Sair",
    field_overview: "Visão Geral do Campo",
    good_morning: "Bom dia, Agricultor.",
    promising_growth: "Seus campos estão mostrando um crescimento promissor hoje.",
    diagnostic_activity: "Sua Atividade de Diagnóstico",
    live_conditions: "Condições em Tempo Real",
    weather_outlook: "Previsão do Tempo",
    partly_cloudy: "Parcialmente Nublado",
    current_monitoring: "Monitoramento Atual",
    view_all_observations: "Ver Todas as Observações",
    total_diagnoses: "Total de Diagnósticos",
    active_recovery: "Recuperação Ativa",
    health_score: "Pontuação de Saúde do Campo",
    efficiency_bonus: "Eficiência",
    ask_anything: "Pergunte qualquer coisa...",
    send: "Enviar",
    scanning: "Analisando sua cultura...",
    diagnosis_found: "DIAGNÓSTICO DE IA ENCONTRADO",
    confidence: "Confiança",
    recovery_journal: "Gostaria de iniciar um diário de recuperação para esta cultura?",
    start_monitoring: "Iniciar Monitoramento",
    another_specimen: "Analisar Outro Espécime",
    language: "Idioma",
    theme: "Tema",
    dark_mode: "Modo Escuro",
    light_mode: "Modo Claro"
  },
  es: {
    dashboard: "Panel",
    crop_doctor: "Doctor de Cultivos",
    recovery_tracker: "Seguimiento de Recuperación",
    daily_tasks: "Tareas Diarias",
    weather: "Clima",
    guidance: "Guía",
    ai_coach: "Entrenador IA",
    account: "Cuenta",
    logout: "Cerrar sesión",
    field_overview: "Vista General del Campo",
    good_morning: "Buenos días, Agricultor.",
    promising_growth: "Sus campos muestran un crecimiento prometedor hoy.",
    diagnostic_activity: "Su Actividad de Diagnóstico",
    live_conditions: "Condiciones en Vivo",
    weather_outlook: "Perspectiva del Tiempo",
    partly_cloudy: "Parcialmente Nublado",
    current_monitoring: "Monitoreo Actual",
    view_all_observations: "Ver Todas las Observaciones",
    total_diagnoses: "Diagnósticos Totales",
    active_recovery: "Recuperación Activa",
    health_score: "Puntuación de Salud del Campo",
    efficiency_bonus: "Eficiencia",
    ask_anything: "Pregunta cualquier cosa...",
    send: "Enviar",
    scanning: "Analizando su cultivo...",
    diagnosis_found: "DIAGNÓSTICO DE IA ENCONTRADO",
    confidence: "Confianza",
    recovery_journal: "¿Le gustaría iniciar un diario de recuperación para este cultivo?",
    start_monitoring: "Iniciar Monitoreo",
    another_specimen: "Analizar Otro Espécimen",
    language: "Idioma",
    theme: "Tema",
    dark_mode: "Modo Oscuro",
    light_mode: "Modo Claros"
  },
  zh: {
    dashboard: "控制面板",
    crop_doctor: "作物医生",
    recovery_tracker: "恢复追踪",
    daily_tasks: "每日任务",
    weather: "天气",
    guidance: "指导",
    ai_coach: "AI 教练",
    account: "账户",
    logout: "登出",
    field_overview: "田间概览",
    good_morning: "早安，农夫。",
    promising_growth: "您的田地今天展现出良好的生长势头。",
    diagnostic_activity: "您的诊断活动",
    live_conditions: "实时状况",
    weather_outlook: "天气预报",
    partly_cloudy: "多云",
    current_monitoring: "当前监测",
    view_all_observations: "查看所有观察结果",
    total_diagnoses: "总诊断数",
    active_recovery: "活跃恢复中",
    health_score: "田间健康评分",
    efficiency_bonus: "效率",
    ask_anything: "咨询任何问题...",
    send: "发送",
    scanning: "正在分析您的作物...",
    diagnosis_found: "发现 AI 诊断结果",
    confidence: "置信度",
    recovery_journal: "您想为该作物启动恢复日志吗？",
    start_monitoring: "开始监测",
    another_specimen: "分析另一个标本",
    language: "语言",
    theme: "主题",
    dark_mode: "深色模式",
    light_mode: "浅色模式"
  },
  hi: {
    dashboard: "डैशबोर्ड",
    crop_doctor: "फसल डॉक्टर",
    recovery_tracker: "रिकवरी ट्रैकर",
    daily_tasks: "दैनिक कार्य",
    weather: "मौसम",
    guidance: "मार्गदर्शन",
    ai_coach: "एआई कोच",
    account: "खाता",
    logout: "लॉगआउट",
    field_overview: "खेत का अवलोकन",
    good_morning: "सुप्रभात, किसान भाई।",
    promising_growth: "आज आपके खेतों में अच्छी वृद्धि दिख रही है।",
    diagnostic_activity: "आपकी नैदानिक गतिविधि",
    live_conditions: "ताज़ा स्थिति",
    weather_outlook: "मौसम का दृष्टिकोण",
    partly_cloudy: "आंशिक रूप से बादल",
    current_monitoring: "वर्तमान निगरानी",
    view_all_observations: "सभी टिप्पणियाँ देखें",
    total_diagnoses: "कुल निदान",
    active_recovery: "सक्रिय रिकवरी",
    health_score: "खेत का स्वास्थ्य स्कोर",
    efficiency_bonus: "कार्यक्षमता",
    ask_anything: "कुछ भी पूछें...",
    send: "भेजें",
    scanning: "आपकी फसल का विश्लेषण किया जा रहा है...",
    diagnosis_found: "एआई निदान मिला",
    confidence: "विश्वास",
    recovery_journal: "क्या आप इस फसल के लिए रिकवरी जर्नल शुरू करना चाहेंगे?",
    start_monitoring: "निगरानी शुरू करें",
    another_specimen: "दूसरे नमूने का विश्लेषण करें",
    language: "भाषा",
    theme: "थीम",
    dark_mode: "डार्क मोड",
    light_mode: "लाइट मोड"
  },
  am: {
    dashboard: "ዳሽቦርድ",
    crop_doctor: "የሰብል ዶክተር",
    recovery_tracker: "የማገገሚያ መከታተያ",
    daily_tasks: "ዕለታዊ ተግባራት",
    weather: "የአየር ሁኔታ",
    guidance: "መመሪያ",
    ai_coach: "የአይአይ አሰልጣኝ",
    account: "መለያ",
    logout: "ይውጡ",
    field_overview: "የእርሻ አጠቃላይ እይታ",
    good_morning: "እንደምን አደሩ አርሶ አደር።",
    promising_growth: "እርሻዎ ዛሬ ተስፋ ሰጪ እድገት እያሳየ ነው።",
    diagnostic_activity: "የምርመራ እንቅስቃሴዎ",
    live_conditions: "የአሁኑ ሁኔታ",
    weather_outlook: "የአየር ሁኔታ ትንበያ",
    partly_cloudy: "በከፊል ደመናማ",
    current_monitoring: "የአሁኑ ክትትል",
    view_all_observations: "ሁሉንም ምልከታዎች ይመልከቱ",
    total_diagnoses: "ጠቅላላ ምርመራዎች",
    active_recovery: "ንቁ ማገገሚያ",
    health_score: "የእርሻ ጤና ነጥብ",
    efficiency_bonus: "ውጤታማነት",
    ask_anything: "ማንኛውንም ነገር ይጠይቁ...",
    send: "ላክ",
    scanning: "ሰብልዎን በመተንተን ላይ...",
    diagnosis_found: "የአይአይ ምርመራ ተገኝቷል",
    confidence: "እምነት",
    recovery_journal: "ለዚህ ሰብል የማገገሚያ ጆርናል መጀመር ይፈልጋሉ?",
    start_monitoring: "ክትትል ይጀምሩ",
    another_specimen: "ሌላ ናሙና ይተንትኑ",
    language: "ቋንቋ",
    theme: "ገጽታ",
    dark_mode: "ጨለማ ሁነታ",
    light_mode: "ብርሃን ሁነታ"
  },
  ha: {
    dashboard: "Dashboard",
    crop_doctor: "Likiton Shuka",
    recovery_tracker: "Mai Bibiyar Farfadowa",
    daily_tasks: "Ayyukan Kullum",
    weather: "Yanayi",
    guidance: "Jagora",
    ai_coach: "Kocin AI",
    account: "Asusu",
    logout: "Fita",
    field_overview: "Bayanan Fage",
    good_morning: "Ina kwana, Manomi.",
    promising_growth: "Gonakinku suna nuna ci gaba mai kyau yau.",
    diagnostic_activity: "Ayyukan Bincikenku",
    live_conditions: "Yanayin Yanzu",
    weather_outlook: "Hasashen Yanayi",
    partly_cloudy: "Gajimare kadan",
    current_monitoring: "Sa ido na Yanzu",
    view_all_observations: "Duba Duk Abubuwan lura",
    total_diagnoses: "Jimlar Bincike",
    active_recovery: "Farfadowa Mai Aiki",
    health_score: "Makin Lafiyar Fage",
    efficiency_bonus: "Inganci",
    ask_anything: "Tambayi komai...",
    send: "Aika",
    scanning: "Ana nazarin amfanin gonar ku...",
    diagnosis_found: "AN SAMI BINCIKEN AI",
    confidence: "Amincewa",
    recovery_journal: "Kuna son fara jaridar farfadowa ga wannan amfanin gona?",
    start_monitoring: "Fara Sa ido",
    another_specimen: "Yi nazarin Wani Samfurin",
    language: "Harshe",
    theme: "Jigo",
    dark_mode: "Yanayin Duhu",
    light_mode: "Yanayin Haske"
  },
  yo: {
    dashboard: "Dasibodi",
    crop_doctor: "Dókítà Irúgbìn",
    recovery_tracker: "Apasọ Ìmúbọ̀padà",
    daily_tasks: "Àwọn Iṣẹ́ Ojoojúmọ́",
    weather: "Ojú-ọjọ́",
    guidance: "Ìtọ́sọ́nà",
    ai_coach: "Olùkọ́ni AI",
    account: "Àpamọ́",
    logout: "Jáde",
    field_overview: "Ìwo-gbogbo Oko",
    good_morning: "Ẹ kú àárọ̀, Àgbẹ̀.",
    promising_growth: "Àwọn oko rẹ ń fi ìdàgbàsókè tó dára hàn lónìí.",
    diagnostic_activity: "Ìgbòkègbodò Ayẹ̀wò rẹ",
    live_conditions: "Ipò lọ́wọ́lọ́wọ́",
    weather_outlook: "Ìwo Ojú-ọjọ́",
    partly_cloudy: "Ojú-ọjọ́ ti o kún fún àwọsánmà díẹ̀",
    current_monitoring: "Àmójútó lọ́wọ́lọ́wọ́",
    view_all_observations: "Wo Gbogbo Àyẹ̀wò",
    total_diagnoses: "Àpapọ̀ Ayẹ̀wò",
    active_recovery: "Ìmúbọ̀padà lọ́wọ́lọ́wọ́",
    health_score: "Iyì Ìlera Oko",
    efficiency_bonus: "Iṣẹ́-ṣíṣe",
    ask_anything: "Béèrè ohunkohun...",
    send: "Fi ránṣẹ́",
    scanning: "Ayẹ̀wò irúgbìn rẹ lọ́wọ́...",
    diagnosis_found: "A RÍ AYẸ̀WÒ AI",
    confidence: "Ìgbẹ́kẹ̀lé",
    recovery_journal: "Ṣé o fẹ́ bẹ̀rẹ̀ ìwé-ìrántí ìmúbọ̀padà fún irúgbìn yìí?",
    start_monitoring: "Bẹ̀rẹ̀ Àmójútó",
    another_specimen: "Yẹ Irúgbìn Míràn Wò",
    language: "Èdè",
    theme: "Àwọ̀",
    dark_mode: "Ipo Òkùnkùn",
    light_mode: "Ipo Ìmọ́lẹ̀"
  },
  zu: {
    dashboard: "Ideshibhodi",
    crop_doctor: "UDokotela Wezitshalo",
    recovery_tracker: "Ithrekha Yokululama",
    daily_tasks: "Imisebenzi Yansuku zonke",
    weather: "Isimo Sezulu",
    guidance: "Isiqondiso",
    ai_coach: "Umqeqeshi we-AI",
    account: "I-akhawunti",
    logout: "Phuma",
    field_overview: "Ukubuka Konke Kwasensimini",
    good_morning: "Sawubona, Mlimi.",
    promising_growth: "Amasimu akho abonisa ukukhula okuthembisayo namuhla.",
    diagnostic_activity: "Umsebenzi Wakho Wokuxilonga",
    live_conditions: "Izimo Zamanje",
    weather_outlook: "Isimo Sezulu",
    partly_cloudy: "Kuyashintshashintsha",
    current_monitoring: "Ukuqapha Kwamanje",
    view_all_observations: "Buka Konke Okuboniwe",
    total_diagnoses: "Zonke Izinhlobo Zokuxilonga",
    active_recovery: "Ukululama Okusebenzayo",
    health_score: "Amaphuzu Ezempilo Yasensimini",
    efficiency_bonus: "Ukunemba",
    ask_anything: "Buza noma yini...",
    send: "Thumela",
    scanning: "Ihlaziya isitshalo sakho...",
    diagnosis_found: "KUTHOLAKALE UKUXILONGA KWE-AI",
    confidence: "Ukuzethemba",
    recovery_journal: "Ungathanda ukuqala ijenali yokululama yalesi sitshalo?",
    start_monitoring: "Qala Ukuqapha",
    another_specimen: "Hlaziya Esinye Isitshalo",
    language: "Ulimi",
    theme: "Itimu",
    dark_mode: "Imodi Emnyama",
    light_mode: "Imodi Ebkhanyayo"
  },
  ig: {
    dashboard: "Dashboard",
    crop_doctor: "Dọkịta Ihe Ịkụ n'Ubi",
    recovery_tracker: "Onye Ndepụta Nlọghachi",
    daily_tasks: "Ọrụ Kwa Ụbọchị",
    weather: "Ihu Igwe",
    guidance: "Ntuziaka",
    ai_coach: "Onye Ọzụzụ AI",
    account: "Akaụntụ",
    logout: "Pụta",
    field_overview: "Nlele ubi",
    good_morning: "Ị mụọla, Onye Ọrụ Ugbo.",
    promising_growth: "Ubi gị na-egosi uto dị mma taa.",
    diagnostic_activity: "Ọrụ Nchọpụta Gị",
    live_conditions: "Ihu Igwe Ugbu a",
    weather_outlook: "Nlereanya Ihu Igwe",
    partly_cloudy: "Urukpuru ole na ole",
    current_monitoring: "Nleba anya ugbu a",
    view_all_observations: "Lee Ihe niile Achọpụtara",
    total_diagnoses: "Nchọpụta niile",
    active_recovery: "Nlọghachi Na-arụ Ọrụ",
    health_score: "Akara Ahụike Ubi",
    efficiency_bonus: "Ịrụ Ọrụ nke ọma",
    ask_anything: "Jụọ ihe ọ bụla...",
    send: "Zipụ",
    scanning: "Na-enyocha ihe ọkụkụ gị...",
    diagnosis_found: "ACHỌPỤTARA NCHỌPỤTA AI",
    confidence: "Ntụkwasị obi",
    recovery_journal: "Ị ga-achọ ịmalite akwụkwọ nlekọta maka ihe ọkụkụ a?",
    start_monitoring: "Malite Nleba anya",
    another_specimen: "Nyochaa Ihe Ọzọ",
    language: "Asụsụ",
    theme: "Isiokwu",
    dark_mode: "Ọchịchịrị",
    light_mode: "Ìhè"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(() => {
    return (localStorage.getItem('cropfree_locale') as Locale) || 'en';
  });

  const { user } = useAuth(); // We can sync with user profile if needed

  const setLocale = (newLocale: Locale) => {
    setLocaleState(newLocale);
    localStorage.setItem('cropfree_locale', newLocale);
    document.documentElement.lang = newLocale;
    document.documentElement.dir = newLocale === 'ar' ? 'rtl' : 'ltr';
  };

  useEffect(() => {
    document.documentElement.lang = locale;
    document.documentElement.dir = locale === 'ar' ? 'rtl' : 'ltr';
  }, [locale]);

  const t = (key: string): string => {
    return translations[locale][key] || translations['en'][key] || key;
  };

  const isRTL = locale === 'ar';

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
