import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';
import { useAuth } from './AuthContext';

export type Locale = 'en' | 'fr' | 'pt' | 'ar' | 'es' | 'zh' | 'hi' | 'rw' | 'sw' | 'am' | 'ha' | 'yo' | 'zu' | 'ig';

interface LanguageContextType {
  locale: Locale;
  setLocale: (locale: Locale) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

export const translations: Record<Locale, Record<string, string>> = {
  en: {
    dashboard: "Dashboard",
    crop_doctor: "Crop Doctor",
    recovery_tracker: "Recovery Tracker",
    daily_tasks: "Daily Tasks",
    weather: "Weather",
    guidance: "Guidance",
    ai_coach: "AI Coach",
    account: "Account",
    logout: "Logout",
    field_overview: "Field Overview",
    good_morning: "Good morning, Farmer.",
    promising_growth: "Your fields are showing promising growth today.",
    diagnostic_activity: "Your Diagnostic Activity",
    live_conditions: "Live Conditions",
    weather_outlook: "Weather Outlook",
    partly_cloudy: "Partly Cloudy",
    current_monitoring: "Current Monitoring",
    view_all_observations: "View All Observations",
    total_diagnoses: "Total Diagnoses",
    active_recovery: "Active Recovery",
    health_score: "Field Health Score",
    efficiency_bonus: "Efficiency",
    ask_anything: "Ask anything...",
    send: "Send",
    scanning: "Analyzing your crop...",
    diagnosis_found: "AI DIAGNOSIS FOUND",
    confidence: "Confidence",
    recovery_journal: "Would you like to start a recovery journal for this crop?",
    start_monitoring: "Start Monitoring",
    another_specimen: "Analyze Another Specimen",
    language: "Language",
    theme: "Theme",
    dark_mode: "Dark Mode",
    light_mode: "Light Mode",
    navigation: "Navigation",
    mon: "Mon",
    tue: "Tue",
    wed: "Wed",
    thu: "Thu",
    fri: "Fri",
    sat: "Sat",
    sun: "Sun",
    crop_care: "Crops under your care",
    recovering_robust: "Recovering & Robust",
    dashboard_short: "Feed",
    scan_short: "Scan",
    crops_short: "Crops",
    plan_short: "Plan",
    you_short: "You",
    coach_greeting: "Good morning. I'm your digital agricultural coach. Whether it's a suspicious leaf pattern or climate concerns, I'm here to think through it with you. How is your field today?",
    coach_error: "I encountered a minor connection issue. Shall we try that thought again?",
    great_shot: "Great shot.",
    check_crops_title: "Let's check your crops.",
    ready_opinion: "Ready for an expert opinion? Our AI is standing by.",
    capture_photo_tip: "Capture a clear photo of the leaves or stem. We'll identify any issues in seconds.",
    confirm_analyze: "Confirm & Analyze",
    identifying_patterns: "\"Identifying patterns invisible to the human eye. Almost there.\"",
    save_diagnosis: "Save Diagnosis to History",
    diagnosis_saved: "Diagnosis saved to history.",
    start_crop_scan: "Start Crop Scan",
    diagnostic_status: "Diagnostic Status",
    biosphere_score: "98% Biosphere Score",
    active_observations: "Active Observations Status",
    crops_warning_signs: "Crops showing warning signs",
    requiring_attention: "Requiring attention",
    overview_stress_detected: "Attention: Biometric stress detected in recent crops. Implementation of precision remedial sequences is recommended.",
    overview_status_stable: "Agriculture status remains stable. All vegetative parameters within optimal range.",
    activity_stream: "Activity Stream",
    scan_timeline: "Diagnostic Scan Timeline",
    realtime_uplink: "Real-time Uplink Active",
    kigali_weather_station: "Kigali Weather Station",
    feels_like: "Feels Like",
    humidity: "Humidity",
    weather_advice_warm: "Current warm weather is ideal for planting and vegetative growth cycles.",
    live_management: "Live Management",
    recent_diagnostic_scans: "Recent Diagnostic Scans",
    view_all_history: "View All History",
    no_scans_found: "No Crop Scans Found",
    no_scans_desc: "Begin your crop diagnostic journey now by testing your first crop picture!",
    soil_profile: "Soil Profile",
    soil_profile_desc: "Continuous soil mineral level and pH audits.",
    pest_activity: "Pest Activity",
    pest_activity_desc: "Fungal and parasite density tracking.",
    yield_forecast: "Yield Forecast",
    yield_forecast_desc: "Estimated biological growth rate modeling.",
    crop_health: "Crop Health",
    crop_health_desc: "Integrity checks on broad leaf systems.",
    diagnostics_log: "Diagnostics Log",
    recovery_status_badge: "Recovery Status",
    biological_status: "Biological Status",
    secure_field: "Secure Field.",
    protect_farm_data: "Protect your farm data. Verify details and access 60 days of premium access.",
    daily_routine_planner: "Daily Routine Planner",
    farming_checklist_tasks: "Farming Checklist Tasks",
    tasks_intro_desc: "Organize fertilizing schedules, irrigation frequencies and pesticide applications. Check off once completed.",
    close_form: "Close Form",
    create_task: "Create Task",
    task_title: "Task Title",
    task_title_placeholder: "Enter task title (e.g., Water East Corn Sector)",
    task_desc: "Task Description",
    task_desc_placeholder: "Enter short details...",
    task_priority: "Task Priority",
    priority_helper_text: "High priority tasks will be sorted and bubbled to the top of the interface automatically.",
    cancel: "Cancel",
    save_task: "Save Task",
    farming_efficiency: "Farmland Checklist Efficiency",
    checklist_progress_status: "Checklist Progress Status",
    completed_text: "completed",
    tasks_completed: "tasks completed",
    no_tasks_title: "No tasks planned yet",
    no_tasks_desc: "Write down your fertilizing schedules, irrigation windows, or weeding tasks to optimize yields.",
    create_first_task: "Create First Task",
    toast_marked_incomplete: "Task marked incomplete.",
    toast_task_completed: "Task completed successfully.",
    toast_task_created: "New task created.",
    toast_task_update_failed: "Failed to update task.",
    toast_task_save_failed: "Failed to save new task.",
    toast_task_deleted: "Task deleted.",
    toast_task_delete_failed: "Failed to delete task.",
    loading_task_planner: "Loading task planner...",
    ai_coach_title: "AI Crop & Farmland Coach",
    personalized_advisor: "Personalized Advisor",
    coach_intro_desc: "Get straightforward advice from our smart farming guide. Ask about soil, irrigation, or pest cures.",
    coach_version: "Coach version 2.4",
    coach_cabin: "Coach Consultation Cabin",
    online_status: "ONLINE",
    ask_coach_placeholder: "Ask your coach anything...",
    primary_recomm: "Primary Recommendation",
    morning_irrigation_title: "Regulate Morning Irrigation",
    morning_irrigation_desc: "We detect slight warmth trends. Initiate 6 AM drip sequences to preserve shallow moisture parameters.",
    fully_synced: "Fully Synced",
    advice_engine_ready: "Bio-Intelligence Advice Engine Ready",
    weather_planting: "Weather & Planting",
    maize_yield_forecast: "Maize Yield Forecast",
    weather_planting_desc: "Current high-pressure weather trends represent perfect conditions for planting and organic seed bedding.",
    water_management: "Water Management",
    soil_moisture_score: "Soil Moisture Score",
    water_management_desc: "Your watering schedules are fully matched with this week's rainfall probability to prevent excess runoff.",
    coach_custom_greeting: "Hello! I am your CropFree AI coach. Ask me questions like 'How to cure root rot' or 'Best fertilizer for maize in Rwanda'!",
    atmospheric_conditions: "Atmospheric Conditions",
    meteorological_feed: "Meteorological Feed",
    weather_intro_desc: "Track current and upcoming weather for Kigali to manage irrigation, pesticide applications, and general crop safety.",
    celsius: "Celsius",
    live_station_link: "Live Station Link",
    max_min: "Max / Min",
    air_humidity: "Air Humidity",
    wind_velocity: "Wind Velocity",
    rain_forecast: "Rain Forecast",
    weekly_strategy: "Weekly Farmland Strategy",
    environmental_advisor: "Environmental Impact Advisor",
    weather_advice_humidity: "High air humidity speeds up leaf fungus. Inspect leaves with Crop Doctor frequently.",
    weather_advice_temp: "Warm temperatures will dry soil quickly. Increase soil moisture check frequency.",
    weather_advice_rain: "High chance of rainfall. Pause artificial watering today to save water and protect root soil.",
    weather_advice_perfect: "Weather conditions look perfect. Perfect windows for standard crop care and organic composting schedules.",
    today: "Today",
    retry_connection: "Retry Connection",
    weather_unreachable: "Weather Report Unreachable",
    weather_not_configured: "The Weather API key is not configured. Please supply a valid key in the settings tab to unlock meteorology.",
    sync_weather: "Synchronizing Live Weather Feed...",
    guidance_title: "Soil & Farmland Health Advisor",
    expert_guidance: "Expert Guidance",
    guidance_intro_desc: "Real-time farm health intelligence, crop protection alerts, and detailed soil analysis algorithms.",
    field_soil_quality: "Field Soil Quality Diagnostic",
    current_soil_profile: "Current Soil Profile",
    soil_profile_detail: "Your fields show high nutrient capacity and excellent chemical balancing, perfect for high-yield staple grains.",
    nitrogen_level: "NITROGEN LEVEL",
    soil_ph_range: "SOIL PH RANGE",
    potassium_ratio: "POTASSIUM RATIO",
    phosphorus: "PHOSPHORUS",
    level_optimal: "High (Optimal)",
    level_neutral: "6.8 (Neutral)",
    level_good_balance: "Good Balance",
    level_excellent: "Excellent",
    soil_health_score: "Overall Soil Health Score",
    soil_health_rating: "Excellent Bio-Systems Health",
    next_checkup: "Next Soil Checkup",
    june_14: "June 14th",
    live_monitoring_log: "Live Monitoring Log",
    pest_surveillance: "Local Pest & Spore Surveillance",
    aphid_spreads: "Leaf Aphid Spreads",
    stem_fungal: "Stem Fungal spores",
    root_insect: "Root Insect activity",
    low_risk: "Low Risk",
    elevated_risk: "Elevated Risk",
    safe_status: "Safe Status",
    sector_b4: "Sector B4",
    west_field: "West Field",
    east_hydro: "East Hydro Axis",
    checked_2h_ago: "Checked 2h ago",
    active_live: "Active Live",
    checked_12h_ago: "Checked 12h ago",
    biomarker_status: "Bio-Marker Status",
    priority_suffix: "Priority",
    central_repo: "Central Information Repository",
    intelligence_heading: "Intelligence.",
    intelligence_desc: "Knowledge is the primary catalyst for sustainable yields. Access and study verified agricultural documentation.",
    search_placeholder_repo: "Query database for pathogens, tips, or protocols...",
    execute_query: "Execute Query",
    neural_tutorials: "Neural Tutorials",
    tutorials_desc: "Visual protocols to master AI scanning procedures, recovery logs and agricultural network configurations.",
    biological_almanac: "Biological Almanac",
    almanac_desc: "A comprehensive digital library referencing symptoms, pathogen lifecycles, and organic curing strategies.",
    scanning_precision: "Scanning Precision",
    scanning_precision_desc: "Master high-fidelity agricultural documentation protocols to maximize AI detection accuracy.",
    item_init_seq: "Initialization Sequence",
    item_tracker_dep: "Tracker Deployment",
    item_neural_sync: "Neural Synchronization",
    item_rice_path: "Rice Pathogens",
    item_maize_nut: "Maize Nutrition Deficiencies",
    item_wheat_rust: "Wheat & Grain Rust",
    item_photon_opt: "Photon Optimization",
    item_sympt_track: "Symptom Tracking",
    item_env_context: "Environmental Context",
    common_anomalies: "Common Anomalies.",
    common_anomalies_desc: "Protocol assistance & infrastructure support for offline synchronization and diagnostic errors.",
    knowledge_base_btn: "Knowledge Base",
    expert_liaison: "Expert Liaison.",
    expert_liaison_desc: "Direct uplink to specialized agricultural nodes and agronomists located across your province.",
    uplink_conn_btn: "Uplink Connection",
    verified_info_node: "Verified Information Node: 782-Sigma",
    strategic_aug: "Strategic Augmentation",
    supreme_tier: "Supreme Tier.",
    supreme_tier_desc: "Unlock unrestricted diagnostic bandwidth, advanced biosphere modeling, and 24/7 expert agricultural access.",
    per_binary_cycle: "per binary cycle",
    limited_access: "Limited Access.",
    feature_unlimited_scans: "Unlimited diagnostic scans.",
    feature_realtime_sync: "Real-time biological sync.",
    feature_expert_uplink: "Direct expert uplink v9.4.",
    feature_atmospheric: "Atmospheric synthesis.",
    currency_strategy: "CURRENCY GATEWAY STRATEGY",
    global_credit: "Global Credit",
    mobile_logic: "Mobile Logic",
    init_sub_btn: "Initialize Transformation Sequence",
    sub_processing_btn: "Synchronizing Matrix Hub...",
    node_secured: "NODE SECURED",
    twentyfour_seven_terminal: "24/7 TERMINAL",
    neural_link_severed: "Neural Link Severed.",
    trial_expired_desc_full: "Your preliminary evaluation phase has concluded. Access to active scanning and recovery trackers is temporarily restricted. Upgrade to the supreme protocol to unlock fields.",
    upgrade_required: "Upgrade Required",
    toast_secure_payment: "This would initiate a secure payment protocol in a production environment.",
    interface_protocols: "Interface Protocols",
    station_region: "Station Region",
    global_ke: "Global-KE",
    crop_scan_diagnosis: "Crop Scan Diagnosis",
    scan_instruction: "Upload a clear close-up picture of your plant leaves or stems to identify disease and find solutions.",
    take_photo: "Take Photo",
    use_camera_sub: "Use your camera now",
    upload_file: "Upload File",
    pick_picture_sub: "Pick a picture from device",
    drag_drop_sub: "Drag and drop your crop picture here too",
    start_ai_analysis: "Start AI Crop Analysis",
    take_new_pic: "Take New Card",
    upload_different: "Upload Different",
    analyzing_plant_tissue: "Analyzing Plant Tissue...",
    analyzing_desc: "Checking picture matrices for dynamic disease indicators. This should only take 2-4 seconds.",
    diagnose_result: "Diagnose Result",
    ai_confidence_level: "AI Confidence Level",
    observations_label: "Observations",
    medical_analysis_label: "Medical Analysis",
    symptoms_found_label: "Symptoms Found on Leaves",
    other_conditions_label: "Other Conditions Considered",
    treatment_guide_label: "Treatment Guide",
    read_action_details: "Read Action Details",
    start_monitoring_progress: "Start Monitoring Progress",
    start_new_diagnosis: "Start New Diagnosis",
    save_to_history_btn: "Save to Diagnostic History",
    toast_crop_moved: "Crop moved to your recovery tracker.",
    acknowledge_back_btn: "Acknowledge & Back To Diagnostic",
    treatment_sequences: "Treatment Sequences",
    active_action_list: "Active Action List",
    active_recovery_tracker: "Active Recovery Tracker",
    tracker_intro_desc: "Monitor treatment progress of your recently diagnosed crops. Complete tasks to restore plant health.",
    search_placeholder: "Search crop or disease name...",
    tracker_empty_title: "Crop Tracker Is Empty",
    tracker_empty_desc: "Scan a sick plant leaf using the Crop Doctor to start a guided treatment monitoring cycle.",
    back_to_list: "Back to List",
    active_treatment_plan: "Active Treatment Plan",
    crop_diagnosis_label: "Crop Diagnosis",
    tracked_since: "Tracked since",
    recovery_progress_label: "Recovery Progress",
    plant_fully_cured: "Plant fully cured!",
    keep_completing: "Keep completing steps",
    health_check_needed: "Health Check Needed",
    check_crop_cured: "Check If Crop Is Cured",
    check_crop_cured_desc: "Please take or upload a new photo of this plant using your phone to confirm the infection is gone.",
    upload_health_check_btn: "Upload Health Check Pic",
    verified_healthy: "Verified Healthy!",
    infection_remains: "Infection remains",
    curing_checklist_title: "Curing Step Checklist",
    next_to_accomplish: "Next To Accomplish",
    checklist_badge_tip: "Tip",
    checklist_badge_task: "Task",
    toast_complete_previous: "Please complete the previous treatment step first.",
    toast_cannot_undo: "Cannot undo this step because later steps are already completed.",
    toast_step_completed: "Treatment step completed successfully.",
    toast_recovery_confirmed: "Great news! Plant recovery confirmed.",
    toast_disease_remains: "Notice: Plant shows signs of disease. Keep following treatment guide.",
    toast_crop_removed_tracker: "Crop removed from tracker.",
    toast_crop_delete_failed: "Failed to delete crop record. Please try again.",
    toast_verification_error: "Verification process error. Please try again.",
    delete_tracker_confirm: "Delete Tracker?",
    cannot_be_undone: "This action cannot be undone.",
    delete_btn: "Delete",
    deleting_btn: "Deleting...",
    restoration_label: "Restoration",
    saved_label_date: "Saved",
    view_tasks_link: "View Tasks",
    agriculture_progress: "Agriculture Progress",
    dark_mode_toggle: "Dark Mode",
    light_mode_toggle: "Light Mode",
    workspace: "Workspace",
    trial_plan: "Trial",
    supreme_plan: "Supreme",
    filter_languages: "Filter languages...",
    trial_access_limited: "Biological Access Limited",
    trial_access_limited_desc: "Your evaluation period has reached its final harvest. To maintain access to precision AI diagnostics, transition to our premium infrastructure.",
    upgrade_protocol_btn: "Upgrade Protocol — $2.99/mo",
    loading_intelligence: "Loading intelligence dashboard...",
    onboarding_logo_sub: "CropFree.",
    onboarding_logo_sub_desc: "Precision Intelligence",
    onboarding_hero_title: "Empowering your Harvest.",
    onboarding_hero_desc: "Join thousands of smallholder farmers using real-time crop disease detection and recovery tracking platforms to optimize crop outputs.",
    onboarding_stat_accuracy: "98%",
    onboarding_stat_accuracy_lbl: "Accuracy Rate",
    onboarding_stat_support: "24/7",
    onboarding_stat_support_lbl: "Global Support",
    onboarding_step1_label: "01 / The Mission",
    onboarding_step1_title: "Guardians of the Soil.",
    onboarding_step1_desc: "We bridge the gap between AI-driven intelligence and traditional farming to create zero-hunger communities sustainably.",
    onboarding_step2_label: "02 / Guhanga Udushya",
    onboarding_step2_title: "Guided Restoration.",
    onboarding_step2_scan_lbl: "Diagnostic Scan",
    onboarding_step2_scan_desc: "Identify symptoms in 500ms using any camera device.",
    onboarding_step2_journal_lbl: "Recovery Journal",
    onboarding_step2_journal_desc: "Step-by-step healing protocols designed for smallholders.",
    onboarding_step3_label: "03 / Reliability",
    onboarding_step3_title: "Global Standard.",
    onboarding_step3_eco_lbl: "Sustainable Ecosystems",
    onboarding_step3_eco_desc: "Helping farmers protect biodiversity and improve general soil fertility ratios.",
    onboarding_continue_btn: "Continue Journey",
    onboarding_skip_btn: "Skip",
    onboarding_secure_field_lbl: "Secure Field.",
    onboarding_secure_field_desc: "Protect your farm data and access 60 days of premium access.",
    onboarding_google_signin: "Authenticate with Telephone",
    phone_auth_instructions: "Enter your telephone number to receive an SMS verification code for instant dashboard access.",
    telephone_number: "Telephone Number",
    phone_format_hint: "Standard international format starting with country prefix (e.g. +250 or +1).",
    send_sms_btn: "Send Verification Code",
    enter_sms_code: "Enter Code.",
    sms_sent_to: "SMS code has been dispatched. Enter the 6-digit verification code sent to:",
    sms_code_label: "6-Digit SMS Verification Code",
    verify_btn: "Verify & Access Dashboard",
    back_to_phone_btn: "Change Phone Number",
    onboarding_terms: "Terms of Service",
    onboarding_privacy: "Privacy Policy",
    tutorial_tag: "AGRITECH PLATFORM INTEL",
    tutorial_title: "Welcome to Smart Agritech AI",
    tutorial_desc: "Detect crop diseases, track recovery, and get smart farming guidance powered by precision AI models.",
    tutorial_get_started: "Get Started",
    tutorial_skip_intro: "Skip Intro",
    tutorial_ready_yields: "Ready to maximize your harvest yields",
    tutorial_system_guidance: "System Guidance",
    tutorial_slide: "Slide",
    tutorial_of: "of",
    tutorial_disease_title: "Crop Disease Detection",
    tutorial_disease_desc: "Take a photo or upload crop images to detect diseases instantly using advanced machine learning models.",
    tutorial_recovery_title: "Recovery Tracking",
    tutorial_recovery_desc: "Track your crop recovery progress step by step with our interactive remediation checklist and progress bars.",
    tutorial_smart_title: "Smart Recommendations",
    tutorial_smart_desc: "Receive AI-powered farming advice customized for your fields, soil moisture parameters, and regional weather forecast.",
    tutorial_dashboard_title: "Dashboard Overview",
    tutorial_dashboard_desc: "Monitor all your farm data, alert parameters, task lists, and regional weather stations in one powerful control center.",
    tutorial_prev_btn: "Prev",
    tutorial_next_btn: "Next",
    tutorial_calib_complete_tag: "CALIBRATION COMPLETE",
    tutorial_calib_complete_title: "You’re ready to start smart farming!",
    tutorial_calib_complete_desc: "Step into your futuristic agricultural control console and supercharge your production with precision intelligence.",
    tutorial_enter_dashboard_btn: "Enter Dashboard",
    records: "Records",
    default_practice_1: "Regular watering of normal plant soil",
    default_practice_2: "Cutting off old or heavily diseased leaves",
    default_practice_3: "Adding compost or organic nutrients",
    default_practice_4: "Checking and maintaining soil quality",
    default_practice_5: "Keeping protective soil covers",
    status_validating: "Validating",
    status_in_recovery: "In Recovery",
    status_diagnosed: "Diagnosed",
    status_recovered: "Recovered",
    status_inspecting: "Inspecting",
    severity_label: "Severity",
    severity_critical: "Critical",
    severity_high: "High",
    severity_moderate: "Moderate",
    severity_low: "Low",
    toast_failed_update_step: "Failed to update step.",
    deleting: "Deleting...",
    onboarding_agreement_prefix: "By entering, you agree to our ",
    onboarding_agreement_suffix: ".",
    and: " & "
  },
  fr: {
    dashboard: "Tableau de Bord",
    crop_doctor: "Docteur de Culture",
    recovery_tracker: "Suivi de Récupération",
    daily_tasks: "Tâches Quotidiennes",
    weather: "Météo",
    guidance: "Conseils",
    ai_coach: "Coach IA",
    account: "Compte",
    logout: "Déconnexion",
    field_overview: "Aperçu du Champ",
    good_morning: "Bonjour, Fermier.",
    promising_growth: "Vos champs montrent une croissance prometteuse aujourd'hui.",
    diagnostic_activity: "Votre Activité Diagnostique",
    live_conditions: "Conditions en Direct",
    weather_outlook: "Perspectives Météo",
    partly_cloudy: "Partiellement Nuageux",
    current_monitoring: "Surveillance Actuelle",
    view_all_observations: "Voir Toutes les Observations",
    total_diagnoses: "Diagnostics Totaux",
    active_recovery: "Récupération Active",
    health_score: "Score de Santé du Champ",
    efficiency_bonus: "Efficacité",
    ask_anything: "Demandez n'importe quoi...",
    send: "Envoyer",
    scanning: "Analyse de votre récolte...",
    diagnosis_found: "DIAGNOSTIC IA TROUVÉ",
    confidence: "Confiance",
    recovery_journal: "Souhaitez-vous commencer un journal de récupération pour cette culture ?",
    start_monitoring: "Commencer la Surveillance",
    another_specimen: "Analyser un Autre Spécimen",
    language: "Langue",
    theme: "Thème",
    dark_mode: "Mode Sombre",
    light_mode: "Mode Clair",
    navigation: "Navigation",
    mon: "Lun",
    tue: "Mar",
    wed: "Mer",
    thu: "Jeu",
    fri: "Ven",
    sat: "Sam",
    sun: "Dim",
    crop_care: "Cultures sous votre garde",
    recovering_robust: "En récupération & Robustes",
    dashboard_short: "Flux",
    scan_short: "Scanner",
    crops_short: "Cultures",
    plan_short: "Plan",
    you_short: "Vous"
  },
  ar: {
    dashboard: "لوحة القيادة",
    crop_doctor: "طبيب المحاصيل",
    recovery_tracker: "متتبع التعافي",
    daily_tasks: "المهام اليومية",
    weather: "الطقس",
    guidance: "التوجيه",
    ai_coach: "مدرب الذكاء الاصطناعي",
    account: "الحساب",
    logout: "تسجيل الخروج",
    field_overview: "نظرة عامة على الحقل",
    good_morning: "صباح الخير أيها المزارع.",
    promising_growth: "تظهر حقولك نموًا واعدًا اليوم.",
    diagnostic_activity: "نشاطك التشخيصي",
    live_conditions: "الظروف المباشرة",
    weather_outlook: "توقعات الطقس",
    partly_cloudy: "غائم جزئيًا",
    current_monitoring: "المراقبة الحالية",
    view_all_observations: "عرض جميع الملاحظات",
    total_diagnoses: "إجمالي التشخيصات",
    active_recovery: "التعافي النشط",
    health_score: "درجة صحة الحقل",
    efficiency_bonus: "الكفاءة",
    ask_anything: "اسأل أي شيء...",
    send: "إرسال",
    scanning: "تحليل محصولك...",
    diagnosis_found: "تم العثور على تشخيص الذكاء الاصطناعي",
    confidence: "الثقة",
    recovery_journal: "هل ترغب في بدء سجل تعافي لهذا المحصول؟",
    start_monitoring: "بدء المراقبة",
    another_specimen: "تحليل عينة أخرى",
    language: "اللغة",
    theme: "المظهر",
    dark_mode: "الوضع الداكن",
    light_mode: "الوضع الفاتح",
    navigation: "التنقل",
    mon: "الإثنين",
    tue: "الثلاثاء",
    wed: "الأربعاء",
    thu: "الخميس",
    fri: "الجمعة",
    sat: "السبت",
    sun: "الأحد",
    crop_care: "المحاصيل تحت رعايتك",
    recovering_robust: "تتعافى وقوية",
    dashboard_short: "الخلاصة",
    scan_short: "مسح",
    crops_short: "المحاصيل",
    plan_short: "خطة",
    you_short: "أنت"
  },
  rw: {
    dashboard: "Inshamake",
    crop_doctor: "Muganga w'imyaka",
    recovery_tracker: "Gukurikirana imyaka",
    daily_tasks: "Imirimo y'uyu munsi",
    weather: "Iteganyagihe",
    guidance: "Inama",
    ai_coach: "Agasobanuye",
    account: "Konti",
    logout: "Sohoka",
    field_overview: "Ibyerekeye umurima",
    good_morning: "Mwaramutse, Muhinzi.",
    promising_growth: "Imyaka yawe iragaragaza gukura neza uyu munsi.",
    diagnostic_activity: "Ibihe by'isuzuma ryawe",
    live_conditions: "Ibihe by'ubu",
    weather_outlook: "Iteganyagihe",
    partly_cloudy: "Hari ibicu",
    current_monitoring: "Ibirimo gukurikiranwa",
    view_all_observations: "Reba byose",
    total_diagnoses: "Isuzumwa ryose",
    active_recovery: "Irimo gukira",
    health_score: "Amanota y'ubuzima bw'umurima",
    efficiency_bonus: "Umusaruro",
    ask_anything: "Baza ikibazo cyose...",
    send: "Ohereza",
    scanning: "Irimo gusuzuma ibihingwa byanyu...",
    diagnosis_found: "ISUZUMWA RYA AI RYABONETSE",
    confidence: "Icyizere",
    recovery_journal: "Wifuza gutangira inyandiko yo gukurikirana iki gihingwa?",
    start_monitoring: "Tangira gukurikirana",
    another_specimen: "Susa ikindi gihingwa",
    language: "Ururimi",
    theme: "Igaragara",
    dark_mode: "Umwijima",
    light_mode: "Urumuri",
    navigation: "Ibyiciro",
    mon: "Kbe",
    tue: "Kbo",
    wed: "Kgt",
    thu: "Kne",
    fri: "Kga",
    sat: "Snd",
    sun: "Mgu",
    crop_care: "Ibihingwa witaho",
    recovering_robust: "Ibirimo gukira neza",
    dashboard_short: "Inshamake",
    scan_short: "Isuzuma",
    crops_short: "Ibihingwa",
    plan_short: "Gahunda",
    you_short: "Konti",
    coach_greeting: "Mwaramutse? Ndi umujyanama wawe mu buhinzi mu buryo bw'ikoranabuhanga rya AI. Mbaza ikibazo cyose ku bimenyetso ku mababi cyangwa iby'ikirere, dufatanye kubikemura. Umurima wawe umeze ute uyu munsi?",
    coach_error: "Nagize ikibazo gito cy'itumanaho. Twongere kugerageza gato?",
    great_shot: "Ifoto ifashwe neza cyane.",
    check_crops_title: "Reka tuzuze ibihingwa byawe ubu.",
    ready_opinion: "Witeguye kumva inama z'ikoranabuhanga rya AI? Dufate ifoto ubu.",
    capture_photo_tip: "Fata ifoto igaragara neza y'ibibabi cyangwa igiti cy'igihingwa. Turasubiza mu masegonda make.",
    confirm_analyze: "Emeza ubone isuzuma",
    identifying_patterns: "\"Turi kureba ibimenyetso bitagaragarira amaso y'abantu. Tegereza gato.\"",
    save_diagnosis: "Bika ibyavuye mu isuzuma",
    diagnosis_saved: "Isuzuma ryabitswe ku rwibutso rwawe.",
    start_crop_scan: "Tangira Isuzuma ry'Imyaka",
    diagnostic_status: "Uko Isuzuma Rihagaze",
    biosphere_score: "Amanota y'Ubutaka 98%",
    active_observations: "Urugero rw'Ibyamamaye",
    crops_warning_signs: "Ibihingwa bigaragaza ibibazo",
    requiring_attention: "Bikeneye gukurikiranwa",
    overview_stress_detected: "Icyitonderwa: Hari ibibazo byagaragaye mu bihingwa byawe. Turakugira inama yo gutangira kubivura uyu munsi.",
    overview_status_stable: "Imyaka yawe ihagaze neza cyane. Nta bibazo byagaragayemo uyu munsi ugereranyije.",
    activity_stream: "Ibyakozwe mu Murima",
    scan_timeline: "Igihe cy'Isuzuma ry'Imyaka",
    realtime_uplink: "Ihuza ryorekeye igihe",
    kigali_weather_station: "Iteganyagihe rya Kigali",
    feels_like: "Urugero rwo Kumva",
    humidity: "Ubuhehere",
    weather_advice_warm: "Ibihe byiza bishyushye bihuye neza no gutera n'imikurire y'ibihingwa.",
    live_management: "Ibibera mu Murima",
    recent_diagnostic_scans: "Isuzumwa rya vuba cyane",
    view_all_history: "Reba Ibyakozwe Byose",
    no_scans_found: "Nta Suzuma ry'Imyaka Ryabonetse",
    no_scans_desc: "Tangira isuzuma ry'imyaka yawe uyu munsi mu gufata ifoto y'igihingwa!",
    soil_profile: "imiterere y'ubutaka",
    soil_profile_desc: "Gushishoza imyunyu ngugu n'urugero rwa pH mu butaka kenshi.",
    pest_activity: "Ubukana bw'Ibyonnyi",
    pest_activity_desc: "Gukurikirana imiyege n'ibindi byonnyi byangiza ubutaka.",
    yield_forecast: "Ibipimo by'Umusaruro",
    yield_forecast_desc: "Ibipimo byo gukura n'umusaruro uzaBoneka bishobora kuboneka.",
    crop_health: "Ubuzima bw'Ibihingwa",
    crop_health_desc: "Gupima ubunini bw'amababi n'imikurire nyayo.",
    diagnostics_log: "Ibyakozwe mu Isuzuma",
    recovery_status_badge: "Uko Bikira",
    biological_status: "Uko Ubuzima Buhagaze",
    secure_field: "Urutonde Rukomeye.",
    protect_farm_data: "Linda ibiranga umurima wawe. Injira kugira ngo ufungure gukurikirana n'uburenganzira bw'iminsi 60.",
    daily_routine_planner: "Guhanga Imirimo y'Ubuhi",
    farming_checklist_tasks: "Urutonde rw'imirimo yo mu murima",
    tasks_intro_desc: "Panga ibihe byo gushyiramo ifumbire, kuhira, n'imiti y'ibyonnyi. Shyiraho akamenyetso iyo birangiye uyu munsi.",
    close_form: "Funga ifishi",
    create_task: "Kora Umurimo",
    task_title: "Umutwe w'Umurimo",
    task_title_placeholder: "Andika umutwe w'umurimo (urugero: Kuhira ibigori)",
    task_desc: "Ibisobanuro by'Umurimo",
    task_desc_placeholder: "Andika ibisobanuro bigufi (urugero: kureba umubyimba)...",
    task_priority: "Urugero rw'Igikurikiye",
    priority_helper_text: "Imirimo yihutirwa ishyirwa mbere mu rutonde mu buryo bwikora kandi vuba.",
    cancel: "Guhagarika",
    save_task: "Bika Umurimo",
    farming_efficiency: "Umuvuduko w'Imirimo yo mu Murima",
    checklist_progress_status: "Uko Imirimo Ihagaze",
    completed_text: "byarangiye",
    tasks_completed: "imirimo yarangiye",
    no_tasks_title: "Nta mirimo irapangwa",
    no_tasks_desc: "Andika ibihe byo gushyiramo ifumbire, guhira, n'indi mirimo kugira ngo ugire umusaruro mwiza cyane.",
    create_first_task: "Kora Umurimo wa Mbere",
    toast_marked_incomplete: "Umurimo washyizwe mu kitarangiye ubu.",
    toast_task_completed: "Umurimo washojwe neza cyane.",
    toast_task_created: "Umurimo mushya washyizweho neza.",
    toast_task_update_failed: "Guhindura umurimo byanze.",
    toast_task_save_failed: "Kubika umurimo mushya byanze.",
    toast_task_deleted: "Umurimo wasisbwe neza.",
    toast_task_delete_failed: "Gusiba umurimo byanze.",
    loading_task_planner: "Irimo gutegura imirimo...",
    ai_coach_title: "Umuyobozi wa AI ku Myaka n'Umurima",
    personalized_advisor: "Inama ku Giti Cyawe",
    coach_intro_desc: "Habwa inama zumvikana neza zivuye ku muyobozi wacu ufite ikoranabuhanga rya AI. Baza iby'ubutaka, imiti, cyangwa ibyonnyi.",
    coach_version: "Umuyobozi AI Verisiyo 2.4",
    coach_cabin: "Icyumba cy'Inama hamwe na Muganga AI",
    online_status: "KURI ORI",
    ask_coach_placeholder: "Andika ibibazo ubaze ugufasha uyu munsi...",
    primary_recomm: "Inama Y'ibanze",
    morning_irrigation_title: "Kugenzura Guhira mu Gitondo",
    morning_irrigation_desc: "Hari ubushyuhe buke bwiyongera. Uhira mu gitondo saa kumi n'ebyiri (6 AM) ukoresheje udutonyanga kugira ngo ubuhehere bugaruke neza.",
    fully_synced: "Byasanywe Byose",
    advice_engine_ready: "Ikoranabuhanga ry'Inama ku Myaka Ryiteguye",
    weather_planting: "Iteganyagihe n'Ugushyira mu Butaka",
    maize_yield_forecast: "Ibipimo by'Umusaruro w'Ibigori",
    weather_planting_desc: "Ibihe byiza bifite ubuhehere buke birahuye neza no gushyira imbuto n imikurire y'ubutaka.",
    water_management: "Imicungire y'Amazi",
    soil_moisture_score: "Ubuhehere bw'Ubutaka",
    water_management_desc: "Ibihe byo kuhira bihuye neza n'imvura iteganyijwe muri iri cyumweru, bikurinda gusesagura amazi no kurinda imizi.",
    coach_custom_greeting: "Mwaramutse! Ndi umuyobozi wawe wa CropFree AI. Mbaza ibibazo byose ku buhinzi, nka 'uko barinda kubora kw'imizi' cyangwa 'ifumbire nziza y'ibigori mu Rwanda'!",
    atmospheric_conditions: "Ibyerekeye Ibihe by'Ikirere",
    meteorological_feed: "Amakuru y'Iteganyagihe",
    weather_intro_desc: "Kurikirana ibihe by'ikirere uyu munsi n'iminsi iri imbere muri Kigali kugira ngo ucunge neza kuhira, kwica ibyonnyi n'umutekano w'ibihingwa.",
    celsius: "Selsiyusi",
    live_station_link: "Ihuza ryo ku Gikoresho Nyabwo",
    max_min: "Ubushyuhe Bwinshi / Bukecye",
    air_humidity: "Ubuhehere bw'Ikirere",
    wind_velocity: "Umuvuduko w'Umuyaga",
    rain_forecast: "Amahirwe y'Imvura",
    weekly_strategy: "Inshyamake y'Icyumweru",
    environmental_advisor: "Umujyanama ku Ikirere",
    weather_advice_humidity: "Ubuhehere bwo mu kirere bworohereza imiyege ku mababi. Rebera kenshi na Muganga w'Imyaka.",
    weather_advice_temp: "Ubushyuhe buratuma ubutaka bwuma vuba cyane. Genzura ubuhehere bw'ubutaka kenshi.",
    weather_advice_rain: "Hari amahirwe menshi y'imvura. Hagarika kuhira uyu munsi kugira ngo urinde amazi n'imizi.",
    weather_advice_perfect: "Ikirere kimeze neza cyane. Ni ibihe byiza byo kwitaho n'imyaka no gushyiramo ifumbire y'imborera.",
    today: "Uyu munsi",
    retry_connection: "Gusa Nanone",
    weather_unreachable: "Iteganyagihe Ntabwo Riboneka",
    weather_not_configured: "Urufunguzo rwa Weather API ntirwakonfiguriwe. Genda mu ma-settings kugira ngo urushyireho we!",
    sync_weather: "Hano Iteganyagihe Rya Kuri Ori...",
    guidance_title: "Umujyanama ku Buzima bw'Ubutaka n'Imyaka",
    expert_guidance: "Inama z'Inzobere",
    guidance_intro_desc: "Amakuru n'inama ku buzima bw'umurima, kurinda imyaka, n'ubuzima bw'ubutaka bwawe mu buryo bugezweho.",
    field_soil_quality: "Isuzuma ry'Ubutaka bwo mu Umurima",
    current_soil_profile: "Imiterere y'Ubutaka bw'Ubu",
    soil_profile_detail: "Ubutaka bwawe bufite intungamubiri zihagije, zifasha imikurire y'ibirayi cyangwa ibigori mu Rwanda ubu.",
    nitrogen_level: "URUGERO RWA NITROJENI",
    soil_ph_range: "URUGERO RWA PH",
    potassium_ratio: "URUGERO RWA POTASIYUMU",
    phosphorus: "FOSIFORE",
    level_optimal: "Heza (Byiza)",
    level_neutral: "6.8 (Nta kibazo)",
    level_good_balance: "Urugero rwiza",
    level_excellent: "Byiza cyane",
    soil_health_score: "Amanota y'Ubuzima bw'Ubutaka",
    soil_health_rating: "Ibihingwa Bifite Ubuzima Bukomeye",
    next_checkup: "Isuzuma ry'Ubutaka Ritaha",
    june_14: "Kamena 14",
    live_monitoring_log: "Amakuru y'Igenzura ry'Ubu",
    pest_surveillance: "Igenzura ry'Ibyonnyi n'Imiyege",
    aphid_spreads: "Ibyonnyi ku Mababi (Aphids)",
    stem_fungal: "Imiyege ku Giti (Fungus)",
    root_insect: "Ibyonnyi mu Mizi y'Ibihingwa",
    low_risk: "Icyago Gike",
    elevated_risk: "Icyago Gikomeye",
    safe_status: "Birinzwe",
    sector_b4: "Icyiciro B4",
    west_field: "Umurima w'Iburengerazuba",
    east_hydro: "Icyiciro cy'Iburasirazuba",
    checked_2h_ago: "Yagenzuwe mu masaha 2 ashize",
    active_live: "Bikiriho",
    checked_12h_ago: "Yagenzuwe mu masaha 12 ashize",
    biomarker_status: "Uko Ubuzima Bugenzurwa",
    priority_suffix: "Ubutumwa bukurikiye",
    central_repo: "Ahanyuzwa Amakuru n'Ubumenyi",
    intelligence_heading: "Ubwenge n'Ubumenyi.",
    intelligence_desc: "Ubumenyi ni cyo kintu cy'ingenzi mu gufata neza isi n'imyaka. Reba ibipimo n'amakuru byose hano.",
    search_placeholder_repo: "Saka amakuru ku bijyanye n'indwara, inama, cyangwa uburyo bwo kuzivura...",
    execute_query: "Saka Amakuru",
    neural_tutorials: "Ibisobanuro Bikomeye",
    tutorials_desc: "Uburyo bufasha gusobanukirwa n'ikoreshwa rya gahunda yo gukurikirana imyaka.",
    biological_almanac: "Igitabo cy'Indwara z'Ibihingwa",
    almanac_desc: "Inkoranyabusobanuro ku ndwara n'ibibazo bikunze kugaragara mu buhinzi.",
    scanning_precision: "Isuzuma Ryizewe",
    scanning_precision_desc: "Uburyo bwo gufata amafoto neza kugira ngo isuzuma rigende neza cyane.",
    item_init_seq: "Uburyo bwo Gutangira",
    item_tracker_dep: "Gushyira mu bikorwa isuzuma",
    item_neural_sync: "Guza imashini n'ubutaka",
    item_rice_path: "Indwara z'Umuceri",
    item_maize_nut: "Intungamubiri zibuze mu Bigori",
    item_wheat_rust: "Indwara y'Ingano",
    item_photon_opt: "Gutegura urumuri neza",
    item_sympt_track: "Gukurikirana ibimenyetso",
    item_env_context: "Imiterere y'ikirere",
    common_anomalies: "Ibibazo Bikunze Kubaho.",
    common_anomalies_desc: "Ubufasha no gufashwa ku ikoreshwa rya gahunda.",
    knowledge_base_btn: "Soma Ibitabo",
    expert_liaison: "Ihuriro ry'Inzobere.",
    expert_liaison_desc: "Ihuza ritaziguye n'inzobere z'ubuhinzi hano mu Rwanda.",
    uplink_conn_btn: "Huza Icyerekezo",
    verified_info_node: "Icyiciro cyapimwe kandi cyizewe: 782-Sigma",
    strategic_aug: "Gutezimbere Ubushobozi",
    supreme_tier: "Supreme Tier.",
    supreme_tier_desc: "Fungura ubushobozi bwose bwo gusuzuma indwara z'imyaka, amakuru arambuye, no guhuzwa n'inzobere z'ubuhinzi.",
    per_binary_cycle: "ku kwezi",
    limited_access: "Gusa ku bantu bake.",
    feature_unlimited_scans: "Gusuzuma imyaka inshuro zose ushaka.",
    feature_realtime_sync: "Ihuza ry'ubuzima bw'umurima rya kuri ori.",
    feature_expert_uplink: "Ihuza rya hafi n'inzobere zo mu Rwanda.",
    feature_atmospheric: "Itegenyagihe n'ikirere rigezweho.",
    currency_strategy: "UBURYO BWO KWISHYURA",
    global_credit: "Ikarita yo Kwishyura",
    mobile_logic: "Kwisheya na Mobile Money (MoMo)",
    init_sub_btn: "Tangira Kwiyandikisha",
    sub_processing_btn: "Tegereza gato...",
    node_secured: "BYARINZWE UYUMUNSI",
    twentyfour_seven_terminal: "UBUFASHA BWA 24/7",
    neural_link_severed: "Gahunda Yakoreshwa Yahagaze.",
    trial_expired_desc_full: "Igihe cy'igerageza cyararangiye. Nta burenganzira ufite bwo gusuzuma no gukurikirana ibihingwa mu buryo ubyifuza. Koresha Supreme protocol ufungure umurima.",
    upgrade_required: "Koresha Supreme cyuzuye",
    toast_secure_payment: "Kwishyura bizatangizwa mu buryo bwizewe mugihe pologaramu yagiye hanze we.",
    interface_protocols: "Uburyo bwo gukoresha",
    station_region: "Icyerekezo cy'aho uherereye",
    global_ke: "Rwanda-Kigali",
    crop_scan_diagnosis: "Isuzuma ry'Imyaka",
    scan_instruction: "Shyiraho ifoto igaragara neza y'ibibabi cyangwa giti cy'igihingwa kugirango tumenye icyo kirwaye tuyivure.",
    take_photo: "Fata Ifoto",
    use_camera_sub: "Koresha kigenerano ubu",
    upload_file: "Shiraho Ifoto",
    pick_picture_sub: "Hitamo ifoto muri terefone",
    drag_drop_sub: "Cyangwa ukureho ukayishyira hano ubu",
    start_ai_analysis: "Tangira Isuzuma rya AI",
    take_new_pic: "Fata Ifoto Nshya",
    upload_different: "Shiraho Iyindi",
    analyzing_plant_tissue: "AI Irimo Gusuzuma Icyatsi...",
    analyzing_desc: "AI irimo kureba amashusho no gushakisha indwara n'ibyago. Biratwara amasegonda 2-4 gusa.",
    diagnose_result: "Ibyavuye mu Isuzuma",
    ai_confidence_level: "Urugero rw'Icyizere cya AI",
    observations_label: "Ibyagaragaye",
    medical_analysis_label: "Ubusobanuro bw'Inzobere",
    symptoms_found_label: "Ibimenyetso by'Indwara ku Mababi",
    other_conditions_label: "Zimwe mu ndwara zisa n'izi mbiri",
    treatment_guide_label: "Uburyo bwo kuyivura neza",
    read_action_details: "Reba Amabwiriza",
    start_monitoring_progress: "Tangira Gukurikirana Uko Kirimo Gukira ubu",
    start_new_diagnosis: "Kora Isuzuma Rishya",
    save_to_history_btn: "Bika ku byakozwe",
    toast_crop_moved: "Ihingwa Ryashyizwe mu Igerageza ryo Gukira.",
    acknowledge_back_btn: "Ndabyumvise, Subira ku Isuzuma",
    treatment_sequences: "Intambwe zo Kuvura",
    active_action_list: "Ibikorwa Bihari",
    active_recovery_tracker: "Gukurikirana Ibihingwa Birimo Gukira",
    tracker_intro_desc: "Kurikirana uko ibihingwa byakozweho isuzuma birimo gukira. Kora imirimo usabwa kugira ngo ibihingwa bikire neza.",
    search_placeholder: "Shakisha izina rya crop cyangwa indwara...",
    tracker_empty_title: "Nta gihingwa kirimo gukurikiranwa we",
    tracker_empty_desc: "Soma ifoto y'ibimera bikurwaye ukokesheje Muganga w'Imyaka kugira ngo utangire isuzuma ryo kubivura hano ubu.",
    back_to_list: "Subira ku Rutonde",
    active_treatment_plan: "Gahunda yo Kuvura Igihingwa",
    crop_diagnosis_label: "Indwara y'Ibihingwa",
    tracked_since: "Byakurikiranwe kuva ubu",
    recovery_progress_label: "Uko Kirimo Gukira neza",
    plant_fully_cured: "Amanota 100%! Igihingwa cyarakize neza!",
    keep_completing: "Emeza andi mabwiriza asigaye yo kuvura",
    health_check_needed: "Gupima Ubuzima bwayo birakenewe cyane",
    check_crop_cured: "Genzura niba igihingwa cyarakize ubu",
    check_crop_cured_desc: "Nyamuneka fata ifoto cyangwa ushyireho ifoto nshya y'iki gihingwa kugira ngo AI yemeze niba indwara yarashize rwose.",
    upload_health_check_btn: "Shyiraho Ifoto yo Gupima",
    verified_healthy: "Byemejwe: Kiracyeye Cyane rwose!",
    infection_remains: "Infection iracyarimo mu bimera",
    curing_checklist_title: "Urutonde rw'Intambwe zo Kuvura",
    next_to_accomplish: "Igikurikiyeho Gukorwa ubu",
    checklist_badge_tip: "Inama",
    checklist_badge_task: "Umurimo",
    toast_complete_previous: "Nyamuneka banza wemeze intambwe ibanziriza iyi.",
    toast_cannot_undo: "Ntushobora gusubira inyuma kuko hari izindi ntambwe wamaze kwemeza we.",
    toast_step_completed: "Intambwe yemejwe neza cyane.",
    toast_recovery_confirmed: "Amakuru meza! Gukira kw'igihingwa kwemejwe neza.",
    toast_disease_remains: "Ubwitange: Igihingwa kiracyafite ibimenyetso by'indwara. Komeza gukurikiza amabwiriza.",
    toast_crop_removed_tracker: "Igihingwa cyasibwe mu gukurikiranwa.",
    toast_crop_delete_failed: "Gusiba igihingwa byanze. Ongera ugerageze.",
    toast_verification_error: "Gupima byagize ikibazo. Ongera ugerageze.",
    delete_tracker_confirm: "Gusiba iki gihingwa mu gukira?",
    cannot_be_undone: "Iki gikorwa ntigishobora gusubirwamo na rimwe.",
    delete_btn: "Siba",
    deleting_btn: "Irimo gusiba...",
    restoration_label: "Gukurikira",
    saved_label_date: "Yabitswe",
    view_tasks_link: "Reba Ibisabwa",
    agriculture_progress: "Gukurikirana ku Muhinzi",
    dark_mode_toggle: "Umwijima",
    light_mode_toggle: "Urumuri",
    workspace: "Workspace",
    trial_plan: "Gerageza",
    supreme_plan: "Supreme Tier",
    filter_languages: "Gungura indimi...",
    trial_access_limited: "Igihe Cyapfuye Muri Evaluation",
    trial_access_limited_desc: "Igihe cy'igerageza cyararangiye ubu. Koresha Supreme Tier kugira ngo urusheho gusuzuma no kuvura imyaka yawe isigaye.",
    upgrade_protocol_btn: "Upgrade Protocol — $2.99 ku Kwezi",
    loading_intelligence: "Irimo gushyira m'umurima iboneka...",
    onboarding_logo_sub: "CropFree.",
    onboarding_logo_sub_desc: "Ikoranabuhanga rya Precision",
    onboarding_hero_title: "Kongera Umusaruro Wawe Nyabwo.",
    onboarding_hero_desc: "Fatanya n'abahinzi bagenzi bawe ibihumbi bakoresha isuzuma ryamashusho rya AI ndetse no gukurikirana imikurire y'imyaka.",
    onboarding_stat_accuracy: "98%",
    onboarding_stat_accuracy_lbl: "Urugero rw'Icyizere",
    onboarding_stat_support: "24/7",
    onboarding_stat_support_lbl: "Ubufasha Ubwo Arikwo Bose",
    onboarding_step1_label: "01 / Intego",
    onboarding_step1_title: "Kugenzura Ubutaka Bwacu.",
    onboarding_step1_desc: "Duhuza ikoranabuhanga rya AI n'ubuhinzi busanzwe kugira ngo turwanye inzara mu buryo burambye.",
    onboarding_step2_label: "02 / Guhanga Udushya",
    onboarding_step2_title: "Igerageza ryo Gukira.",
    onboarding_step2_scan_lbl: "Isuzuma Ryihuse",
    onboarding_step2_scan_desc: "Gupima ibimenyetso mu masegonda bake ukoresheje terefone yawe.",
    onboarding_step2_journal_lbl: "Inyandiko yo Gukira",
    onboarding_step2_journal_desc: "Intambwe ku yindi z'amabwiriza zigenewe abahinzi.",
    onboarding_step3_label: "03 / Kwizera",
    onboarding_step3_title: "Icyerekezo ku Isi Yose.",
    onboarding_step3_eco_lbl: "Umutekano w'Ubutaka n'Imyaka",
    onboarding_step3_eco_desc: "Gufasha abahinzi kubungabunga ubuhehere n'uburumbuke bw'ubutaka.",
    onboarding_continue_btn: "Komeza Urugendo",
    onboarding_skip_btn: "Simbuka",
    onboarding_secure_field_lbl: "Umurima Urinzwe.",
    onboarding_secure_field_desc: "Rinda amakuru y'umurima wawe kandi ubone uburyo bwa Premium mu minsi 60.",
    onboarding_google_signin: "Injira ukoresheje Terefone",
    phone_auth_instructions: "Yandika nimero ya terefone yawe kugira ngo uboherereze imibare y'ibanga yo kwinjira.",
    telephone_number: "Nimero ya Terefone",
    phone_format_hint: "Uburyo bwemewe mu rwego mpuzamahanga (urugero: +250 cyangwa +1).",
    send_sms_btn: "Yohereza Imibare Y'isuzuma",
    enter_sms_code: "Yandika Imibare.",
    sms_sent_to: "Imibare ihabwa terefone yoherejwe. Yandike hano hejuru yo kwemeza kuri:",
    sms_code_label: "Imibare 6 Yo Kwemeza",
    verify_btn: "Genzura Maze Winjire",
    back_to_phone_btn: "Hindura Nimero ya Terefone",
    onboarding_terms: "Amabwiriza Agenga Porogaramu",
    onboarding_privacy: "Amategeko y'Ibwanziriza",
    tutorial_tag: "AMAKURU Y'IKORANABUHANGA RYA AGRITECH",
    tutorial_title: "Murakaza neza kuri Smart Agritech AI",
    tutorial_desc: "Sura imyaka ibarwaye, gukurikirana ukogukira, kandi ubone inama zuzuye kuri AI zigenewe ubutaka bwawe.",
    tutorial_get_started: "Tangira Urugendo",
    tutorial_skip_intro: "Simbuka Ibisobanuro",
    tutorial_ready_yields: "Witeguye kongera umusaruro uyu munsi",
    tutorial_system_guidance: "Amabwiriza ya Gahunda",
    tutorial_slide: "Urupapuro",
    tutorial_of: "kuri",
    tutorial_disease_title: "Gupima Indwara z'Imyaka",
    tutorial_disease_desc: "Fata ifoto cyangwa ushyireho amashusho y'imyaka kugira ngo upime indwara udatinze ukoresheje AI.",
    tutorial_recovery_title: "Gukurikirana Gukira",
    tutorial_recovery_desc: "Kurikirana uko igihingwa gikira intambwe ku yindi ukoresheje urutonde rw'imirimo.",
    tutorial_smart_title: "Inama Z'Ubwenge",
    tutorial_smart_desc: "Habwa inama za AI zigenewe umurima wawe, ubuhehere bw'ubutaka, hamwe n'iteganyagihe.",
    tutorial_dashboard_title: "Inshamake ya Dashboard",
    tutorial_dashboard_desc: "Genzura amakuru yose y'umurima, ibimenyetso by'ikirere, imirimo, n'iteganyagihe rya Kigali hamwe.",
    tutorial_prev_btn: "Ibanziriza",
    tutorial_next_btn: "Komeza",
    tutorial_calib_complete_tag: "GUKALIBURA KWARANGIYE",
    tutorial_calib_complete_title: "Urakiyeguye Gutangira Ubuhinzi bw'Ikoranabuhanga!",
    tutorial_calib_complete_desc: "Injira mu nshamake nyayo y'umurima bwawe ukomereze umusaruro mwiza cyane ufatanyije na AI.",
    tutorial_enter_dashboard_btn: "Injira mu Dashibodi",
    records: "Ibikorwa",
    default_practice_1: "Kuhirira ubutaka bw'igihingwa buri munsi",
    default_practice_2: "Gukata amababi ashaje cyangwa arwaye cyane",
    default_practice_3: "Gushyiramo imborera cyangwa intungamubiri",
    default_practice_4: "Kugenzura no kubungabunga ubuhehere bw'ubutaka",
    default_practice_5: "Gupfuka ubutaka ngo bukomeze ubuhehere",
    status_validating: "Isuzuma",
    status_in_recovery: "Birimo Kuvurwa",
    status_diagnosed: "Yapimwe",
    status_recovered: "Yakize",
    status_inspecting: "Irakurikiranwa",
    severity_label: "Ubukana",
    severity_critical: "Mbi Cyane",
    severity_high: "Komeye",
    severity_moderate: "Kigereranyije",
    severity_low: "Ntoya",
    toast_failed_update_step: "Guhindura intambwe byanze.",
    deleting: "Irimo gusiba...",
    onboarding_agreement_prefix: "Winjira hano, wemera ",
    onboarding_agreement_suffix: " yacu.",
    and: " & "
  },
  sw: {
    dashboard: "Dashibodi",
    crop_doctor: "Daktari wa Mazao",
    recovery_tracker: "Ufuatiliaji wa Uponyaji",
    daily_tasks: "Kazi za Kila Siku",
    weather: "Hali ya Hewa",
    guidance: "Mwongozo",
    ai_coach: "Kocha wa AI",
    account: "Akaunti",
    logout: "Ondoka",
    field_overview: "Maelezo ya Shamba",
    good_morning: "Habari za asubuhi, Mkulima.",
    promising_growth: "Mashamba yako yanaonyesha ukuaji wa kuridhisha leo.",
    diagnostic_activity: "Shughuli zako za Utambuzi",
    live_conditions: "Hali ya Sasa",
    weather_outlook: "Mtazamo wa Hali ya Hewa",
    partly_cloudy: "Mawingu kiasi",
    current_monitoring: "Ufuatiliaji wa Sasa",
    view_all_observations: "Tazama Maoni Yote",
    total_diagnoses: "Jumla ya Utambuzi",
    active_recovery: "Uponyaji Amilifu",
    health_score: "Alama ya Afya ya Shamba",
    efficiency_bonus: "Ufanisi",
    ask_anything: "Uliza chochote...",
    send: "Tuma",
    scanning: "Kuchunguza zao lako...",
    diagnosis_found: "UTAMBUZI WA AI UMEREPATIKANA",
    confidence: "Uhakika",
    recovery_journal: "Je, ungependa kuanza rekodi ya uponyaji kwa zao hili?",
    start_monitoring: "Anza Kufuatilia",
    another_specimen: "Chunguza Sampuli Nyingine",
    language: "Lugha",
    theme: "Mandhari",
    dark_mode: "Hali ya Giza",
    light_mode: "Hali ya Mwanga"
  },
  pt: {
    dashboard: "Painel",
    crop_doctor: "Doutor de Culturas",
    recovery_tracker: "Rastreador de Recuperação",
    daily_tasks: "Tarefas Diárias",
    weather: "Clima",
    guidance: "Orientação",
    ai_coach: "Coach de IA",
    account: "Conta",
    logout: "Sair",
    field_overview: "Visão Geral do Campo",
    good_morning: "Bom dia, Agricultor.",
    promising_growth: "Seus campos estão mostrando um crescimento promissor hoje.",
    diagnostic_activity: "Sua Atividade de Diagnóstico",
    live_conditions: "Condições em Tempo Real",
    weather_outlook: "Previsão do Tempo",
    partly_cloudy: "Parcialmente Nublado",
    current_monitoring: "Monitoramento Atual",
    view_all_observations: "Ver Todas as Observações",
    total_diagnoses: "Total de Diagnósticos",
    active_recovery: "Recuperação Ativa",
    health_score: "Pontuação de Saúde do Campo",
    efficiency_bonus: "Eficiência",
    ask_anything: "Pergunte qualquer coisa...",
    send: "Enviar",
    scanning: "Analisando sua cultura...",
    diagnosis_found: "DIAGNÓSTICO DE IA ENCONTRADO",
    confidence: "Confiança",
    recovery_journal: "Gostaria de iniciar um diário de recuperação para esta cultura?",
    start_monitoring: "Iniciar Monitoramento",
    another_specimen: "Analisar Outro Espécime",
    language: "Idioma",
    theme: "Tema",
    dark_mode: "Modo Escuro",
    light_mode: "Modo Claro"
  },
  es: {
    dashboard: "Panel",
    crop_doctor: "Doctor de Cultivos",
    recovery_tracker: "Seguimiento de Recuperación",
    daily_tasks: "Tareas Diarias",
    weather: "Clima",
    guidance: "Guía",
    ai_coach: "Entrenador IA",
    account: "Cuenta",
    logout: "Cerrar sesión",
    field_overview: "Vista General del Campo",
    good_morning: "Buenos días, Agricultor.",
    promising_growth: "Sus campos muestran un crecimiento prometedor hoy.",
    diagnostic_activity: "Su Actividad de Diagnóstico",
    live_conditions: "Condiciones en Vivo",
    weather_outlook: "Perspectiva del Tiempo",
    partly_cloudy: "Parcialmente Nublado",
    current_monitoring: "Monitoreo Actual",
    view_all_observations: "Ver Todas las Observaciones",
    total_diagnoses: "Diagnósticos Totales",
    active_recovery: "Recuperación Activa",
    health_score: "Puntuación de Salud del Campo",
    efficiency_bonus: "Eficiencia",
    ask_anything: "Pregunta cualquier cosa...",
    send: "Enviar",
    scanning: "Analizando su cultivo...",
    diagnosis_found: "DIAGNÓSTICO DE IA ENCONTRADO",
    confidence: "Confianza",
    recovery_journal: "¿Le gustaría iniciar un diario de recuperación para este cultivo?",
    start_monitoring: "Iniciar Monitoreo",
    another_specimen: "Analizar Otro Espécimen",
    language: "Idioma",
    theme: "Tema",
    dark_mode: "Modo Oscuro",
    light_mode: "Modo Claros"
  },
  zh: {
    dashboard: "控制面板",
    crop_doctor: "作物医生",
    recovery_tracker: "恢复追踪",
    daily_tasks: "每日任务",
    weather: "天气",
    guidance: "指导",
    ai_coach: "AI 教练",
    account: "账户",
    logout: "登出",
    field_overview: "田间概览",
    good_morning: "早安，农夫。",
    promising_growth: "您的田地今天展现出良好的生长势头。",
    diagnostic_activity: "您的诊断活动",
    live_conditions: "实时状况",
    weather_outlook: "天气预报",
    partly_cloudy: "多云",
    current_monitoring: "当前监测",
    view_all_observations: "查看所有观察结果",
    total_diagnoses: "总诊断数",
    active_recovery: "活跃恢复中",
    health_score: "田间健康评分",
    efficiency_bonus: "效率",
    ask_anything: "咨询任何问题...",
    send: "发送",
    scanning: "正在分析您的作物...",
    diagnosis_found: "发现 AI 诊断结果",
    confidence: "置信度",
    recovery_journal: "您想为该作物启动恢复日志吗？",
    start_monitoring: "开始监测",
    another_specimen: "分析另一个标本",
    language: "语言",
    theme: "主题",
    dark_mode: "深色模式",
    light_mode: "浅色模式"
  },
  hi: {
    dashboard: "डैशबोर्ड",
    crop_doctor: "फसल डॉक्टर",
    recovery_tracker: "रिकवरी ट्रैकर",
    daily_tasks: "दैनिक कार्य",
    weather: "मौसम",
    guidance: "मार्गदर्शन",
    ai_coach: "एआई कोच",
    account: "खाता",
    logout: "लॉगआउट",
    field_overview: "खेत का अवलोकन",
    good_morning: "सुप्रभात, किसान भाई।",
    promising_growth: "आज आपके खेतों में अच्छी वृद्धि दिख रही है।",
    diagnostic_activity: "आपकी नैदानिक गतिविधि",
    live_conditions: "ताज़ा स्थिति",
    weather_outlook: "मौसम का दृष्टिकोण",
    partly_cloudy: "आंशिक रूप से बादल",
    current_monitoring: "वर्तमान निगरानी",
    view_all_observations: "सभी टिप्पणियाँ देखें",
    total_diagnoses: "कुल निदान",
    active_recovery: "सक्रिय रिकवरी",
    health_score: "खेत का स्वास्थ्य स्कोर",
    efficiency_bonus: "कार्यक्षमता",
    ask_anything: "कुछ भी पूछें...",
    send: "भेजें",
    scanning: "आपकी फसल का विश्लेषण किया जा रहा है...",
    diagnosis_found: "एआई निदान मिला",
    confidence: "विश्वास",
    recovery_journal: "क्या आप इस फसल के लिए रिकवरी जर्नल शुरू करना चाहेंगे?",
    start_monitoring: "निगरानी शुरू करें",
    another_specimen: "दूसरे नमूने का विश्लेषण करें",
    language: "भाषा",
    theme: "थीम",
    dark_mode: "डार्क मोड",
    light_mode: "लाइट मोड"
  },
  am: {
    dashboard: "ዳሽቦርድ",
    crop_doctor: "የሰብል ዶክተር",
    recovery_tracker: "የማገገሚያ መከታተያ",
    daily_tasks: "ዕለታዊ ተግባራት",
    weather: "የአየር ሁኔታ",
    guidance: "መመሪያ",
    ai_coach: "የአይአይ አሰልጣኝ",
    account: "መለያ",
    logout: "ይውጡ",
    field_overview: "የእርሻ አጠቃላይ እይታ",
    good_morning: "እንደምን አደሩ አርሶ አደር።",
    promising_growth: "እርሻዎ ዛሬ ተስፋ ሰጪ እድገት እያሳየ ነው።",
    diagnostic_activity: "የምርመራ እንቅስቃሴዎ",
    live_conditions: "የአሁኑ ሁኔታ",
    weather_outlook: "የአየር ሁኔታ ትንበያ",
    partly_cloudy: "በከፊል ደመናማ",
    current_monitoring: "የአሁኑ ክትትል",
    view_all_observations: "ሁሉንም ምልከታዎች ይመልከቱ",
    total_diagnoses: "ጠቅላላ ምርመራዎች",
    active_recovery: "ንቁ ማገገሚያ",
    health_score: "የእርሻ ጤና ነጥብ",
    efficiency_bonus: "ውጤታማነት",
    ask_anything: "ማንኛውንም ነገር ይጠይቁ...",
    send: "ላክ",
    scanning: "ሰብልዎን በመተንተን ላይ...",
    diagnosis_found: "የአይአይ ምርመራ ተገኝቷል",
    confidence: "እምነት",
    recovery_journal: "ለዚህ ሰብል የማገገሚያ ጆርናል መጀመር ይፈልጋሉ?",
    start_monitoring: "ክትትል ይጀምሩ",
    another_specimen: "ሌላ ናሙና ይተንትኑ",
    language: "ቋንቋ",
    theme: "ገጽታ",
    dark_mode: "ጨለማ ሁነታ",
    light_mode: "ብርሃን ሁነታ"
  },
  ha: {
    dashboard: "Dashboard",
    crop_doctor: "Likiton Shuka",
    recovery_tracker: "Mai Bibiyar Farfadowa",
    daily_tasks: "Ayyukan Kullum",
    weather: "Yanayi",
    guidance: "Jagora",
    ai_coach: "Kocin AI",
    account: "Asusu",
    logout: "Fita",
    field_overview: "Bayanan Fage",
    good_morning: "Ina kwana, Manomi.",
    promising_growth: "Gonakinku suna nuna ci gaba mai kyau yau.",
    diagnostic_activity: "Ayyukan Bincikenku",
    live_conditions: "Yanayin Yanzu",
    weather_outlook: "Hasashen Yanayi",
    partly_cloudy: "Gajimare kadan",
    current_monitoring: "Sa ido na Yanzu",
    view_all_observations: "Duba Duk Abubuwan lura",
    total_diagnoses: "Jimlar Bincike",
    active_recovery: "Farfadowa Mai Aiki",
    health_score: "Makin Lafiyar Fage",
    efficiency_bonus: "Inganci",
    ask_anything: "Tambayi komai...",
    send: "Aika",
    scanning: "Ana nazarin amfanin gonar ku...",
    diagnosis_found: "AN SAMI BINCIKEN AI",
    confidence: "Amincewa",
    recovery_journal: "Kuna son fara jaridar farfadowa ga wannan amfanin gona?",
    start_monitoring: "Fara Sa ido",
    another_specimen: "Yi nazarin Wani Samfurin",
    language: "Harshe",
    theme: "Jigo",
    dark_mode: "Yanayin Duhu",
    light_mode: "Yanayin Haske"
  },
  yo: {
    dashboard: "Dasibodi",
    crop_doctor: "Dókítà Irúgbìn",
    recovery_tracker: "Apasọ Ìmúbọ̀padà",
    daily_tasks: "Àwọn Iṣẹ́ Ojoojúmọ́",
    weather: "Ojú-ọjọ́",
    guidance: "Ìtọ́sọ́nà",
    ai_coach: "Olùkọ́ni AI",
    account: "Àpamọ́",
    logout: "Jáde",
    field_overview: "Ìwo-gbogbo Oko",
    good_morning: "Ẹ kú àárọ̀, Àgbẹ̀.",
    promising_growth: "Àwọn oko rẹ ń fi ìdàgbàsókè tó dára hàn lónìí.",
    diagnostic_activity: "Ìgbòkègbodò Ayẹ̀wò rẹ",
    live_conditions: "Ipò lọ́wọ́lọ́wọ́",
    weather_outlook: "Ìwo Ojú-ọjọ́",
    partly_cloudy: "Ojú-ọjọ́ ti o kún fún àwọsánmà díẹ̀",
    current_monitoring: "Àmójútó lọ́wọ́lọ́wọ́",
    view_all_observations: "Wo Gbogbo Àyẹ̀wò",
    total_diagnoses: "Àpapọ̀ Ayẹ̀wò",
    active_recovery: "Ìmúbọ̀padà lọ́wọ́lọ́wọ́",
    health_score: "Iyì Ìlera Oko",
    efficiency_bonus: "Iṣẹ́-ṣíṣe",
    ask_anything: "Béèrè ohunkohun...",
    send: "Fi ránṣẹ́",
    scanning: "Ayẹ̀wò irúgbìn rẹ lọ́wọ́...",
    diagnosis_found: "A RÍ AYẸ̀WÒ AI",
    confidence: "Ìgbẹ́kẹ̀lé",
    recovery_journal: "Ṣé o fẹ́ bẹ̀rẹ̀ ìwé-ìrántí ìmúbọ̀padà fún irúgbìn yìí?",
    start_monitoring: "Bẹ̀rẹ̀ Àmójútó",
    another_specimen: "Yẹ Irúgbìn Míràn Wò",
    language: "Èdè",
    theme: "Àwọ̀",
    dark_mode: "Ipo Òkùnkùn",
    light_mode: "Ipo Ìmọ́lẹ̀"
  },
  zu: {
    dashboard: "Ideshibhodi",
    crop_doctor: "UDokotela Wezitshalo",
    recovery_tracker: "Ithrekha Yokululama",
    daily_tasks: "Imisebenzi Yansuku zonke",
    weather: "Isimo Sezulu",
    guidance: "Isiqondiso",
    ai_coach: "Umqeqeshi we-AI",
    account: "I-akhawunti",
    logout: "Phuma",
    field_overview: "Ukubuka Konke Kwasensimini",
    good_morning: "Sawubona, Mlimi.",
    promising_growth: "Amasimu akho abonisa ukukhula okuthembisayo namuhla.",
    diagnostic_activity: "Umsebenzi Wakho Wokuxilonga",
    live_conditions: "Izimo Zamanje",
    weather_outlook: "Isimo Sezulu",
    partly_cloudy: "Kuyashintshashintsha",
    current_monitoring: "Ukuqapha Kwamanje",
    view_all_observations: "Buka Konke Okuboniwe",
    total_diagnoses: "Zonke Izinhlobo Zokuxilonga",
    active_recovery: "Ukululama Okusebenzayo",
    health_score: "Amaphuzu Ezempilo Yasensimini",
    efficiency_bonus: "Ukunemba",
    ask_anything: "Buza noma yini...",
    send: "Thumela",
    scanning: "Ihlaziya isitshalo sakho...",
    diagnosis_found: "KUTHOLAKALE UKUXILONGA KWE-AI",
    confidence: "Ukuzethemba",
    recovery_journal: "Ungathanda ukuqala ijenali yokululama yalesi sitshalo?",
    start_monitoring: "Qala Ukuqapha",
    another_specimen: "Hlaziya Esinye Isitshalo",
    language: "Ulimi",
    theme: "Itimu",
    dark_mode: "Imodi Emnyama",
    light_mode: "Imodi Ebkhanyayo"
  },
  ig: {
    dashboard: "Dashboard",
    crop_doctor: "Dọkịta Ihe Ịkụ n'Ubi",
    recovery_tracker: "Onye Ndepụta Nlọghachi",
    daily_tasks: "Ọrụ Kwa Ụbọchị",
    weather: "Ihu Igwe",
    guidance: "Ntuziaka",
    ai_coach: "Onye Ọzụzụ AI",
    account: "Akaụntụ",
    logout: "Pụta",
    field_overview: "Nlele ubi",
    good_morning: "Ị mụọla, Onye Ọrụ Ugbo.",
    promising_growth: "Ubi gị na-egosi uto dị mma taa.",
    diagnostic_activity: "Ọrụ Nchọpụta Gị",
    live_conditions: "Ihu Igwe Ugbu a",
    weather_outlook: "Nlereanya Ihu Igwe",
    partly_cloudy: "Urukpuru ole na ole",
    current_monitoring: "Nleba anya ugbu a",
    view_all_observations: "Lee Ihe niile Achọpụtara",
    total_diagnoses: "Nchọpụta niile",
    active_recovery: "Nlọghachi Na-arụ Ọrụ",
    health_score: "Akara Ahụike Ubi",
    efficiency_bonus: "Ịrụ Ọrụ nke ọma",
    ask_anything: "Jụọ ihe ọ bụla...",
    send: "Zipụ",
    scanning: "Na-enyocha ihe ọkụkụ gị...",
    diagnosis_found: "ACHỌPỤTARA NCHỌPỤTA AI",
    confidence: "Ntụkwasị obi",
    recovery_journal: "Ị ga-achọ ịmalite akwụkwọ nlekọta maka ihe ọkụkụ a?",
    start_monitoring: "Malite Nleba anya",
    another_specimen: "Nyochaa Ihe Ọzọ",
    language: "Asụsụ",
    theme: "Isiokwu",
    dark_mode: "Ọchịchịrị",
    light_mode: "Ìhè"
  }
};

export interface Language {
  code: Locale;
  name: string;
}

export const supportedLanguages: Language[] = [
  { code: 'en', name: 'English' },
  { code: 'fr', name: 'Français' },
  { code: 'pt', name: 'Português' },
  { code: 'es', name: 'Español' },
  { code: 'ar', name: 'العربية' },
  { code: 'zh', name: '中文' },
  { code: 'hi', name: 'हिन्दी' },
  { code: 'am', name: 'አማርኛ' },
  { code: 'ha', name: 'Hausa' },
  { code: 'yo', name: 'Yoruba' },
  { code: 'rw', name: 'Ikinyarwanda' },
  { code: 'sw', name: 'Kiswahili' },
  { code: 'zu', name: 'isiZulu' },
  { code: 'ig', name: 'Igbo' },
];

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(() => {
    return (localStorage.getItem('cropfree_locale') as Locale) || 'en';
  });

  const { user } = useAuth(); // We can sync with user profile if needed

  const setLocale = (newLocale: Locale) => {
    setLocaleState(newLocale);
    localStorage.setItem('cropfree_locale', newLocale);
    document.documentElement.lang = newLocale;
    document.documentElement.dir = newLocale === 'ar' ? 'rtl' : 'ltr';
  };

  useEffect(() => {
    document.documentElement.lang = locale;
    document.documentElement.dir = locale === 'ar' ? 'rtl' : 'ltr';
  }, [locale]);

  const t = (key: string): string => {
    if (translations[locale] && translations[locale][key] !== undefined) {
      return translations[locale][key];
    }
    return translations['en']?.[key] || key;
  };

  const isRTL = locale === 'ar';

  return (
    <LanguageContext.Provider value={{ locale, setLocale, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
